## Part 2
This part focuses on using `spark` to analyze NFL data.

The code below imports all required modules for this entire section and runs objects needed to suppress/manage unnecessary warnings.

In [1]:
import os
os.environ['PYARROW_IGNORE_TIMEZONE'] = '1'

import pandas as pd
import numpy as np
import pyspark.pandas as ps

ps.set_option('compute.fail_on_ansi_mode', False)

from pyspark.sql import SparkSession
from pyspark.sql.functions import *

#code needed to manage package warnings -- this spark object is used for both pandas-on-spark and Spark SQL
spark = SparkSession.builder.appName('my_app').config('spark.sql.ansi.enabled', 'false').getOrCreate()

WARNING: Using incubator modules: jdk.incubator.vector
Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
26/03/22 15:46:00 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
26/03/22 15:46:02 WARN SparkSession: Using an existing Spark session; only runtime SQL configurations will take effect.

#### `pandas`-on-Spark

The code below reads in the weekly NFL data from the main filepath in JupyterHub.

In [2]:
NFL = ps.read_csv("weekly_nfl_data.csv")

/opt/tljh/user/envs/pySpark3/lib/python3.9/site-packages/pyspark/pandas/utils.py:1037: PandasAPIOnSparkAdviceWarning: If `index_col` is not specified for `read_csv`, the default index is attached which can cause additional overhead.
  warnings.warn(message, PandasAPIOnSparkAdviceWarning)

Next, we use `.head()` to check out the first 5 rows of the `NFL` dataframe.

In [3]:
NFL.head()

26/03/22 15:46:26 WARN SparkStringUtils: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.

    player_id player_name    player_display_name position position_group headshot_url recent_team  season  week season_type opponent_team  completions  attempts  passing_yards  passing_tds  interceptions  sacks  sack_yards  sack_fumbles  sack_fumbles_lost  passing_air_yards  passing_yards_after_catch  passing_first_downs  passing_epa  passing_2pt_conversions  pacr  dakota  carries  rushing_yards  rushing_tds  rushing_fumbles  rushing_fumbles_lost  rushing_first_downs  rushing_epa  rushing_2pt_conversions  receptions  targets  receiving_yards  receiving_tds  receiving_fumbles  receiving_fumbles_lost  receiving_air_yards  receiving_yards_after_catch  receiving_first_downs  receiving_epa  receiving_2pt_conversions  racr  target_share  air_yards_share  wopr  special_teams_tds  fantasy_points  fantasy_points_ppr
0  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         MIA    1999     1         REG           DEN            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN       16           60.0            1              0.0                   0.0                  4.0     6.248771                        0           1        1              7.0              0                0.0                     0.0                  0.0                          0.0                    0.0       0.292378                          0   0.0      0.052632              NaN   NaN                0.0            12.7                13.7
1  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         MIA    1999     2         REG           ARI            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN        9           33.0            0              0.0                   0.0                  1.0    -1.434950                        0           3        4             18.0              0                0.0                     0.0                  0.0                          0.0                    1.0       0.377009                          0   0.0      0.117647              NaN   NaN                0.0             5.1                 8.1
2  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         MIA    1999     4         REG           BUF            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN        3            2.0            0              0.0                   0.0                  0.0    -1.539952                        0           0        1              0.0              0                0.0                     0.0                  0.0                          0.0                    0.0      -0.699578                          0   NaN      0.023810              NaN   NaN                0.0             0.2                 0.2
3  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         CLE    1999     7         REG            LA            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN        6           27.0            0              0.0                   0.0                  0.0     0.216051                        0           2        2              8.0              0                0.0                     0.0                  0.0                          0.0                    0.0      -0.228454                          0   0.0      0.050000              NaN   NaN                0.0             3.5                 5.5
4  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         CLE    1999     8         REG            NO            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN       13           39.0            0              0.0                   0.0                  2.0    -2.972259                        0           0        0              0.0              0                0.0                     0.0                  0.0                          0.0                    0.0            NaN                          0   NaN           NaN              NaN   NaN                0.0             3.9                 3.9

The code below reports all the column names of the `NFL` dataframe.

In [4]:
NFL.columns

Index(['player_id', 'player_name', 'player_display_name', 'position',
       'position_group', 'headshot_url', 'recent_team', 'season', 'week',
       'season_type', 'opponent_team', 'completions', 'attempts',
       'passing_yards', 'passing_tds', 'interceptions', 'sacks', 'sack_yards',
       'sack_fumbles', 'sack_fumbles_lost', 'passing_air_yards',
       'passing_yards_after_catch', 'passing_first_downs', 'passing_epa',
       'passing_2pt_conversions', 'pacr', 'dakota', 'carries', 'rushing_yards',
       'rushing_tds', 'rushing_fumbles', 'rushing_fumbles_lost',
       'rushing_first_downs', 'rushing_epa', 'rushing_2pt_conversions',
       'receptions', 'targets', 'receiving_yards', 'receiving_tds',
       'receiving_fumbles', 'receiving_fumbles_lost', 'receiving_air_yards',
       'receiving_yards_after_catch', 'receiving_first_downs', 'receiving_epa',
       'receiving_2pt_conversions', 'racr', 'target_share', 'air_yards_share',
       'wopr', 'special_teams_tds', 'fantasy_points', 'fantasy_points_ppr'],
      dtype='object')

Next, we only want to look at QB stats for the seasons 2005 to 2023 (inclusive). Additionally:
- We only want the following columns -
    - `player_display_name`
    - `season`
    - `week`
    - `completions`
    - `attempts`
    - `passing_yards`
    - `passing_tds`
    - `interceptions`
- For each combination of `player_display_name` and `season`, we will find the *sum* and *mean* of each of the statistical quantities in this subsetted dataset
- We will create two new variables by player/season combination:
    - `completion_percentage` = (sum of completions) / (sum of attempts)
    - `td_int_ratio` = (sum of passing tds) / (sum of interceptions)

The code below subsets `NFL` to look at regular season QB stats, specifically for seasons 2005 to 2023, inclusive. The code also subsets the columns of interest. This new object is called `NFL_sub1`.

In [6]:
NFL_sub1 = NFL.loc[(NFL['position'] == 'QB') & 
                   (NFL['season_type'] == 'REG') & 
                   (NFL['season'].between(2005, 2023))] \
              [["player_display_name", "season", "week", "completions",
                "attempts", "passing_yards", "passing_tds", "interceptions"]]

Next, the code below calculates the sum and mean for each of the statistical quantities in this subsetted data for each combination of `player_display_name` and `season`. This new object is called `NFL_sub2`.

In [7]:
NFL_sub2 = NFL_sub1.groupby(["player_display_name", "season"]) \
                    [["completions", "attempts", "passing_yards",
                      "passing_tds", "interceptions"]].agg(['mean', 'sum'])

Finally, we create the two new variables that were previously described! Then, they are added to our already subsetted dataframe (`NFL_sub2`).

In [8]:
cp = NFL_sub2["completions", "sum"] / NFL_sub2["attempts", "sum"] #creates completion_percentage variable
NFL_sub2["completion_percentage"] = cp #adds completion_percentage variable to NFL_sub2

tdir = NFL_sub2["passing_tds", "sum"] / NFL_sub2["interceptions", "sum"] #creates td_int_ratio variable
NFL_sub2["td_int_ratio"] = tdir #adds td_int_ratio variable to NFL_sub2

NFL_sub2.head() #previews final df

                           completions        attempts      passing_yards         passing_tds     interceptions       completion_percentage td_int_ratio
                                  mean  sum       mean  sum          mean     sum        mean sum          mean   sum
player_display_name season
Jake Delhomme       2006     20.230769  263  33.153846  431    215.769231  2805.0    1.307692  17      0.846154  11.0              0.610209     1.545455
Jake Plummer        2005     17.312500  277  28.500000  456    210.375000  3366.0    1.125000  18      0.437500   7.0              0.607456     2.571429
Matt Schaub         2006      3.600000   18   5.400000   27     41.600000   208.0    0.200000   1      0.400000   2.0              0.666667     0.500000
Vince Young         2006     12.266667  184  23.733333  356    146.600000  2199.0    0.800000  12      0.866667  13.0              0.516854     0.923077
Kerry Collins       2007      8.333333   50  13.666667   82     88.500000   531.0    0.000000   0      0.000000   0.0              0.609756          NaN

The final results of the above are saved in the `NFL_sub2` object.

Now, we take `NFL_sub2` and do the following:
- Subset the rows to only include player/season combinations where the sum of attempts is at least 50
- Sort the rows descending by `completion_percentage` and report the first 40 values
- Sort the rows descending by `td_int_ratio` and report the first 40 values

First, we subset the `NFL_sub2` object to only include the rows where the player/season combination sum of attempts is at least 50. This new object is called `NFL_sub3`.

In [9]:
NFL_sub3 = NFL_sub2.loc[NFL_sub2["attempts", "sum"] >= 50]

Next, we sort the rows of `NFL_sub3` descending by `completion_percentage` and report the first 40 values.

In [10]:
NFL_sub3.sort_values("completion_percentage", ascending=False).head(40)

                           completions        attempts      passing_yards         passing_tds     interceptions       completion_percentage td_int_ratio
                                  mean  sum       mean  sum          mean     sum        mean sum          mean   sum
player_display_name season
C.J. Beathard       2023      6.666667   40   8.833333   53     58.166667   349.0    0.166667   1      0.000000   0.0              0.754717          inf
Colt McCoy          2021     10.571429   74  14.142857   99    105.714286   740.0    0.428571   3      0.142857   1.0              0.747475     3.000000
Matt Schaub         2019     10.000000   50  13.400000   67    116.000000   580.0    0.600000   3      0.200000   1.0              0.746269     3.000000
Drew Brees          2018     24.266667  364  32.600000  489    266.133333  3992.0    2.133333  32      0.333333   5.0              0.744376     6.400000
                    2019     25.545455  281  34.363636  378    270.818182  2979.0    2.454545  27      0.363636   4.0              0.743386     6.750000
Mason Rudolph       2023     13.750000   55  18.500000   74    179.750000   719.0    0.750000   3      0.000000   0.0              0.743243          inf
Taysom Hill         2020      5.500000   88   7.562500  121     58.000000   928.0    0.250000   4      0.125000   2.0              0.727273     2.000000
Nick Foles          2018     28.200000  141  39.000000  195    282.600000  1413.0    1.400000   7      0.800000   4.0              0.723077     1.750000
Drew Brees          2017     24.125000  386  33.500000  536    270.875000  4334.0    1.437500  23      0.500000   8.0              0.720149     2.875000
Sam Bradford        2016     26.333333  395  36.800000  552    258.466667  3877.0    1.333333  20      0.333333   5.0              0.715580     4.000000
Drew Brees          2011     29.437500  471  41.250000  660    345.937500  5535.0    2.875000  46      0.875000  14.0              0.713636     3.285714
Colt McCoy          2014     18.200000   91  25.600000  128    211.400000  1057.0    0.800000   4      0.600000   3.0              0.710938     1.333333
Aaron Rodgers       2020     23.250000  372  32.875000  526    268.687500  4299.0    3.000000  48      0.312500   5.0              0.707224     9.600000
Bailey Zappe        2022     16.250000   65  23.000000   92    195.250000   781.0    1.250000   5      0.750000   3.0              0.706522     1.666667
Drew Brees          2009     24.200000  363  34.266667  514    292.533333  4388.0    2.266667  34      0.733333  11.0              0.706226     3.090909
                    2020     22.916667  275  32.500000  390    245.166667  2942.0    2.000000  24      0.500000   6.0              0.705128     4.000000
Joe Burrow          2021     22.875000  366  32.500000  520    288.187500  4611.0    2.125000  34      0.875000  14.0              0.703846     2.428571
Derek Carr          2019     22.562500  361  32.062500  513    253.375000  4054.0    1.312500  21      0.500000   8.0              0.703704     2.625000
Jake Browning       2023     19.000000  171  27.000000  243    215.111111  1936.0    1.333333  12      0.777778   7.0              0.703704     1.714286
Chase Daniel        2019     15.000000   45  21.333333   64    145.000000   435.0    1.000000   3      0.666667   2.0              0.703125     1.500000
Ryan Tannehill      2019     16.750000  201  23.833333  286    228.500000  2742.0    1.833333  22      0.500000   6.0              0.702797     3.666667
Deshaun Watson      2020     23.875000  382  34.000000  544    301.437500  4823.0    2.062500  33      0.437500   7.0              0.702206     4.714286
Alex Smith          2012     15.300000  153  21.800000  218    173.700000  1737.0    1.300000  13      0.500000   5.0              0.701835     2.600000
Kirk Cousins        2018     26.562500  425  37.875000  606    268.625000  4298.0    1.875000  30      0.625000  10.0              0.701320     3.000000
Jamie Martin        2005     15.500000  124  22.125000  177    159.625000  1277.0    0.625000   5      0.875000   7.0              0.700565     0.714286
Drew Brees          2016     29.437500  471  42.062500  673    325.500000  5208.0    2.312500  37      0.937500  15.0              0.699851     2.466667
Tony Romo           2014     20.266667  304  29.000000  435    247.000000  3705.0    2.266667  34      0.600000   9.0              0.698851     3.777778
Matt Ryan           2016     23.312500  373  33.375000  534    309.000000  4944.0    2.375000  38      0.437500   7.0              0.698502     5.428571
Kirk Cousins        2015     23.687500  379  33.937500  543    260.375000  4166.0    1.812500  29      0.687500  11.0              0.697974     2.636364
Geno Smith          2022     23.470588  399  33.647059  572    251.882353  4282.0    1.764706  30      0.647059  11.0              0.697552     2.727273
Chase Daniel        2018     13.250000   53  19.000000   76    128.750000   515.0    0.750000   3      0.500000   2.0              0.697368     1.500000
Carson Wentz        2018     25.363636  279  36.454545  401    279.454545  3074.0    1.909091  21      0.636364   7.0              0.695761     3.000000
Dak Prescott        2023     24.117647  410  34.705882  590    265.647059  4516.0    2.117647  36      0.529412   9.0              0.694915     4.000000
Philip Rivers       2013     23.625000  378  34.000000  544    279.875000  4478.0    2.000000  32      0.687500  11.0              0.694853     2.909091
Tony Romo           2010     24.666667  148  35.500000  213    267.500000  1605.0    1.833333  11      1.166667   7.0              0.694836     1.571429
Kirk Cousins        2023     27.000000  216  38.875000  311    291.375000  2331.0    2.250000  18      0.625000   5.0              0.694534     3.600000
Matt Ryan           2018     26.375000  422  38.000000  608    307.750000  4924.0    2.187500  35      0.437500   7.0              0.694079     5.000000
Brock Purdy         2023     19.250000  308  27.750000  444    267.500000  4280.0    1.937500  31      0.687500  11.0              0.693694     2.818182
Jim Sorgi           2005      8.600000   43  12.400000   62     88.800000   444.0    0.600000   3      0.200000   1.0              0.693548     3.000000
Brandon Weeden      2015     16.166667   97  23.333333  140    173.833333  1043.0    0.833333   5      0.333333   2.0              0.692857     2.500000

Finally, independent of the previous step, we again sort the rows of `NFL_sub3`, this time descending by `td_int_ratio` and report the first 40 values.

In [11]:
NFL_sub3.sort_values("td_int_ratio", ascending=False).head(40)

                           completions        attempts      passing_yards         passing_tds     interceptions       completion_percentage td_int_ratio
                                  mean  sum       mean  sum          mean     sum        mean sum          mean   sum
player_display_name season
Charlie Batch       2006      4.285714   30   7.428571   52     68.142857   477.0    0.714286   5      0.000000   0.0              0.576923          inf
Matt Schaub         2005      4.714286   33   9.142857   64     70.714286   495.0    0.571429   4      0.000000   0.0              0.515625          inf
Todd Collins        2007     16.750000   67  26.250000  105    222.000000   888.0    1.250000   5      0.000000   0.0              0.638095          inf
Troy Smith          2007     10.000000   40  19.000000   76    113.000000   452.0    0.500000   2      0.000000   0.0              0.526316          inf
Jake Locker         2011      6.800000   34  13.200000   66    108.400000   542.0    0.800000   4      0.000000   0.0              0.515152          inf
Brian Hoyer         2016     22.333333  134  33.333333  200    240.833333  1445.0    1.000000   6      0.000000   0.0              0.670000          inf
Nick Foles          2016     18.000000   36  27.500000   55    205.000000   410.0    1.500000   3      0.000000   0.0              0.654545          inf
Derek Anderson      2014     13.000000   65  19.400000   97    140.200000   701.0    1.000000   5      0.000000   0.0              0.670103          inf
Jimmy Garoppolo     2016      7.166667   43  10.500000   63     83.666667   502.0    0.666667   4      0.000000   0.0              0.682540          inf
Matt Moore          2019      9.833333   59  15.166667   91    109.833333   659.0    0.666667   4      0.000000   0.0              0.648352          inf
C.J. Beathard       2020     11.000000   66  17.333333  104    131.166667   787.0    1.000000   6      0.000000   0.0              0.634615          inf
Andy Dalton         2023     17.000000   34  29.000000   58    180.500000   361.0    1.000000   2      0.000000   0.0              0.586207          inf
Mason Rudolph       2023     13.750000   55  18.500000   74    179.750000   719.0    0.750000   3      0.000000   0.0              0.743243          inf
Desmond Ridder      2022     18.250000   73  28.750000  115    177.000000   708.0    0.500000   2      0.000000   0.0              0.634783          inf
C.J. Beathard       2023      6.666667   40   8.833333   53     58.166667   349.0    0.166667   1      0.000000   0.0              0.754717          inf
Tom Brady           2016     24.250000  291  36.000000  432    296.166667  3554.0    2.333333  28      0.166667   2.0              0.673611    14.000000
Nick Foles          2013     15.615385  203  24.384615  317    222.384615  2891.0    2.076923  27      0.153846   2.0              0.640379    13.500000
Josh McCown         2013     18.625000  149  28.000000  224    228.625000  1829.0    1.625000  13      0.125000   1.0              0.665179    13.000000
Aaron Rodgers       2018     23.250000  372  37.312500  597    277.625000  4442.0    1.562500  25      0.125000   2.0              0.623116    12.500000
Damon Huard         2006     14.800000  148  24.400000  244    187.800000  1878.0    1.100000  11      0.100000   1.0              0.606557    11.000000
Aaron Rodgers       2020     23.250000  372  32.875000  526    268.687500  4299.0    3.000000  48      0.312500   5.0              0.707224     9.600000
                    2021     22.875000  366  33.187500  531    257.187500  4115.0    2.312500  37      0.250000   4.0              0.689266     9.250000
Tom Brady           2010     20.250000  324  30.750000  492    243.750000  3900.0    2.250000  36      0.250000   4.0              0.658537     9.000000
Jake Delhomme       2007     18.333333   55  28.666667   86    205.666667   617.0    2.666667   8      0.333333   1.0              0.639535     8.000000
Aaron Rodgers       2014     21.312500  341  32.500000  520    273.812500  4381.0    2.375000  38      0.312500   5.0              0.655769     7.600000
                    2011     22.800000  342  33.400000  501    309.066667  4636.0    3.000000  45      0.400000   6.0              0.682635     7.500000
Drew Brees          2019     25.545455  281  34.363636  378    270.818182  2979.0    2.454545  27      0.363636   4.0              0.743386     6.750000
Aaron Rodgers       2019     22.062500  353  35.562500  569    250.125000  4002.0    1.625000  26      0.250000   4.0              0.620387     6.500000
Drew Brees          2018     24.266667  364  32.600000  489    266.133333  3992.0    2.133333  32      0.333333   5.0              0.744376     6.400000
Patrick Mahomes     2020     26.000000  390  39.200000  588    316.000000  4740.0    2.533333  38      0.400000   6.0              0.663265     6.333333
Tom Brady           2007     24.875000  398  36.125000  578    300.375000  4806.0    3.125000  50      0.500000   8.0              0.688581     6.250000
Russell Wilson      2019     21.312500  341  32.250000  516    256.875000  4110.0    1.937500  31      0.312500   5.0              0.660853     6.200000
David Garrard       2007     17.333333  208  27.083333  325    209.083333  2509.0    1.500000  18      0.250000   3.0              0.640000     6.000000
Matthew Stafford    2010     14.250000   57  24.000000   96    133.750000   535.0    1.500000   6      0.250000   1.0              0.593750     6.000000
Lamar Jackson       2019     17.666667  265  26.733333  401    208.466667  3127.0    2.400000  36      0.400000   6.0              0.660848     6.000000
Dak Prescott        2016     19.437500  311  28.687500  459    229.187500  3667.0    1.437500  23      0.250000   4.0              0.677560     5.750000
Aaron Rodgers       2016     25.062500  401  38.125000  610    276.750000  4428.0    2.500000  40      0.437500   7.0              0.657377     5.714286
Peyton Manning      2013     28.125000  450  41.187500  659    342.312500  5477.0    3.437500  55      0.625000  10.0              0.682853     5.500000
Matt Ryan           2016     23.312500  373  33.375000  534    309.000000  4944.0    2.375000  38      0.437500   7.0              0.698502     5.428571
Alex Smith          2017     22.733333  341  33.666667  505    269.466667  4042.0    1.733333  26      0.333333   5.0              0.675248     5.200000

#### Spark SQL

The code below reads in the weekly NFL data from the main filepath in JupyterHub.

In [12]:
NFL_spark = spark.read.load("weekly_nfl_data.csv",
                            format="csv",
                            sep=",",
                            inferSchema="true",
                            header="true")

Next, we use `.show(5)` to check out the first 5 rows of the `NFL_spark` dataframe.

In [13]:
NFL_spark.show(5)

+----------+-----------+--------------------+--------+--------------+------------+-----------+------+----+-----------+-------------+-----------+--------+-------------+-----------+-------------+-----+----------+------------+-----------------+-----------------+-------------------------+-------------------+-----------+-----------------------+----+------+-------+-------------+-----------+---------------+--------------------+-------------------+-----------+-----------------------+----------+-------+---------------+-------------+-----------------+----------------------+-------------------+---------------------------+---------------------+-------------+-------------------------+----+------------+---------------+----+-----------------+--------------+------------------+
| player_id|player_name| player_display_name|position|position_group|headshot_url|recent_team|season|week|season_type|opponent_team|completions|attempts|passing_yards|passing_tds|interceptions|sacks|sack_yards|sack_fumbles|sack_fumbles_lost|passing_air_yards|passing_yards_after_catch|passing_first_downs|passing_epa|passing_2pt_conversions|pacr|dakota|carries|rushing_yards|rushing_tds|rushing_fumbles|rushing_fumbles_lost|rushing_first_downs|rushing_epa|rushing_2pt_conversions|receptions|targets|receiving_yards|receiving_tds|receiving_fumbles|receiving_fumbles_lost|receiving_air_yards|receiving_yards_after_catch|receiving_first_downs|receiving_epa|receiving_2pt_conversions|racr|target_share|air_yards_share|wopr|special_teams_tds|fantasy_points|fantasy_points_ppr|
+----------+-----------+--------------------+--------+--------------+------------+-----------+------+----+-----------+-------------+-----------+--------+-------------+-----------+-------------+-----+----------+------------+-----------------+-----------------+-------------------------+-------------------+-----------+-----------------------+----+------+-------+-------------+-----------+---------------+--------------------+-------------------+-----------+-----------------------+----------+-------+---------------+-------------+-----------------+----------------------+-------------------+---------------------------+---------------------+-------------+-------------------------+----+------------+---------------+----+-----------------+--------------+------------------+
|00-0000003|       NULL|Abdul-Karim al-Ja...|      RB|            RB|        NULL|        MIA|  1999|   1|        REG|          DEN|          0|       0|          0.0|          0|          0.0|  0.0|       0.0|           0|                0|              0.0|                      0.0|                0.0|       NULL|                      0|NULL|  NULL|     16|         60.0|          1|            0.0|                 0.0|                4.0|   6.248771|                      0|         1|      1|            7.0|            0|              0.0|                   0.0|                0.0|                        0.0|                  0.0|   0.29237816|                        0| 0.0|  0.05263158|           NULL|NULL|              0.0|          12.7|              13.7|
|00-0000003|       NULL|Abdul-Karim al-Ja...|      RB|            RB|        NULL|        MIA|  1999|   2|        REG|          ARI|          0|       0|          0.0|          0|          0.0|  0.0|       0.0|           0|                0|              0.0|                      0.0|                0.0|       NULL|                      0|NULL|  NULL|      9|         33.0|          0|            0.0|                 0.0|                1.0| -1.4349501|                      0|         3|      4|           18.0|            0|              0.0|                   0.0|                0.0|                        0.0|                  1.0|    0.3770089|                        0| 0.0|  0.11764706|           NULL|NULL|              0.0|           5.1|               8.1|
|00-0000003|       NULL|Abdul-Karim al-Ja...|      RB|            RB|        NULL|        MIA|  1999|   4|        REG|          BUF|          0|       0|          0.0|          0|          0.0|  0.0|       0.0|           0|                0|              0.0|                      0.0|                0.0|       NULL|                      0|NULL|  NULL|      3|          2.0|          0|            0.0|                 0.0|                0.0| -1.5399517|                      0|         0|      1|            0.0|            0|              0.0|                   0.0|                0.0|                        0.0|                  0.0|  -0.69957775|                        0|NULL| 0.023809524|           NULL|NULL|              0.0|           0.2|               0.2|
|00-0000003|       NULL|Abdul-Karim al-Ja...|      RB|            RB|        NULL|        CLE|  1999|   7|        REG|           LA|          0|       0|          0.0|          0|          0.0|  0.0|       0.0|           0|                0|              0.0|                      0.0|                0.0|       NULL|                      0|NULL|  NULL|      6|         27.0|          0|            0.0|                 0.0|                0.0|  0.2160509|                      0|         2|      2|            8.0|            0|              0.0|                   0.0|                0.0|                        0.0|                  0.0|  -0.22845396|                        0| 0.0|        0.05|           NULL|NULL|              0.0|           3.5|               5.5|
|00-0000003|       NULL|Abdul-Karim al-Ja...|      RB|            RB|        NULL|        CLE|  1999|   8|        REG|           NO|          0|       0|          0.0|          0|          0.0|  0.0|       0.0|           0|                0|              0.0|                      0.0|                0.0|       NULL|                      0|NULL|  NULL|     13|         39.0|          0|            0.0|                 0.0|                2.0| -2.9722588|                      0|         0|      0|            0.0|            0|              0.0|                   0.0|                0.0|                        0.0|                  0.0|         NULL|                        0|NULL|        NULL|           NULL|NULL|              0.0|           3.9|               3.9|
+----------+-----------+--------------------+--------+--------------+------------+-----------+------+----+-----------+-------------+-----------+--------+-------------+-----------+-------------+-----+----------+------------+-----------------+-----------------+-------------------------+-------------------+-----------+-----------------------+----+------+-------+-------------+-----------+---------------+--------------------+-------------------+-----------+-----------------------+----------+-------+---------------+-------------+-----------------+----------------------+-------------------+---------------------------+---------------------+-------------+-------------------------+----+------------+---------------+----+-----------------+--------------+------------------+
only showing top 5 rows

The code below reports all the column names of the `NFL_spark` dataframe.

In [14]:
NFL_spark.columns

['player_id',
 'player_name',
 'player_display_name',
 'position',
 'position_group',
 'headshot_url',
 'recent_team',
 'season',
 'week',
 'season_type',
 'opponent_team',
 'completions',
 'attempts',
 'passing_yards',
 'passing_tds',
 'interceptions',
 'sacks',
 'sack_yards',
 'sack_fumbles',
 'sack_fumbles_lost',
 'passing_air_yards',
 'passing_yards_after_catch',
 'passing_first_downs',
 'passing_epa',
 'passing_2pt_conversions',
 'pacr',
 'dakota',
 'carries',
 'rushing_yards',
 'rushing_tds',
 'rushing_fumbles',
 'rushing_fumbles_lost',
 'rushing_first_downs',
 'rushing_epa',
 'rushing_2pt_conversions',
 'receptions',
 'targets',
 'receiving_yards',
 'receiving_tds',
 'receiving_fumbles',
 'receiving_fumbles_lost',
 'receiving_air_yards',
 'receiving_yards_after_catch',
 'receiving_first_downs',
 'receiving_epa',
 'receiving_2pt_conversions',
 'racr',
 'target_share',
 'air_yards_share',
 'wopr',
 'special_teams_tds',
 'fantasy_points',
 'fantasy_points_ppr']

Next, we only want to look at QB stats for the seasons 2005 to 2023 (inclusive). Additionally:
- We only want the following columns -
    - `player_display_name`
    - `season`
    - `week`
    - `completions`
    - `attempts`
    - `passing_yards`
    - `passing_tds`
    - `interceptions`
- For each combination of `player_display_name` and `season`, we will find the *sum* and *mean* of each of the statistical quantities in this subsetted dataset
- We will create two new variables by player/season combination:
    - `completion_percentage` = (sum of completions) / (sum of attempts)
    - `td_int_ratio` = (sum of passing tds) / (sum of interceptions)

The code below subsets `NFL_spark` to meet all of the above criteria and also adds the two new variables. This is all accomplished in the one code chunk below. The results are saved as an object called `NFL_spark_ss`.

In [15]:
NFL_spark_ss = NFL_spark.filter((NFL_spark.position == 'QB') & (NFL_spark.season_type == 'REG') &
                                (NFL_spark.season.between(2005,2023))) \
                        .select(["player_display_name", "season", "week", "completions",
                                 "attempts", "passing_yards", "passing_tds", "interceptions"]) \
                        .groupby(["player_display_name", "season"]) \
                        .agg(sum("completions"), avg("completions"), sum("attempts"), avg("attempts"),
                             sum("passing_yards"), avg("passing_yards"), sum("passing_tds"), avg("passing_tds"),
                             sum("interceptions"), avg("interceptions")) \
                        .withColumn("completion_percentage", col("sum(completions)") / col("sum(attempts)")) \
                        .withColumn("td_int_ratio", col("sum(passing_tds)") / col("sum(interceptions)"))

NFL_spark_ss.show(5) #previews resulting df

+-------------------+------+----------------+------------------+-------------+------------------+------------------+------------------+----------------+------------------+------------------+------------------+---------------------+------------------+
|player_display_name|season|sum(completions)|  avg(completions)|sum(attempts)|     avg(attempts)|sum(passing_yards)|avg(passing_yards)|sum(passing_tds)|  avg(passing_tds)|sum(interceptions)|avg(interceptions)|completion_percentage|      td_int_ratio|
+-------------------+------+----------------+------------------+-------------+------------------+------------------+------------------+----------------+------------------+------------------+------------------+---------------------+------------------+
|      Jake Delhomme|  2006|             263| 20.23076923076923|          431| 33.15384615384615|            2805.0|215.76923076923077|              17|1.3076923076923077|              11.0|0.8461538461538461|   0.6102088167053364|1.5454545454545454|
|       Jake Plummer|  2005|             277|           17.3125|          456|              28.5|            3366.0|           210.375|              18|             1.125|               7.0|            0.4375|   0.6074561403508771|2.5714285714285716|
|        Matt Schaub|  2006|              18|               3.6|           27|               5.4|             208.0|              41.6|               1|               0.2|               2.0|               0.4|   0.6666666666666666|               0.5|
|        Vince Young|  2006|             184|12.266666666666667|          356|23.733333333333334|            2199.0|             146.6|              12|               0.8|              13.0|0.8666666666666667|   0.5168539325842697|0.9230769230769231|
|      Kerry Collins|  2007|              50| 8.333333333333334|           82|13.666666666666666|             531.0|              88.5|               0|               0.0|               0.0|               0.0|   0.6097560975609756|              NULL|
+-------------------+------+----------------+------------------+-------------+------------------+------------------+------------------+----------------+------------------+------------------+------------------+---------------------+------------------+
only showing top 5 rows

Now, we take `NFL_spark_ss` and do the following:
- Subset the rows to only include player/season combinations where the sum of attempts is at least 50.
- Sort the rows descending by completion_percentage and report the first 40 values!
- Sort the rows descending by td_int_ratio and report the first 40 values!

First, we show `NFL_spark_ss` subsetted to only include player/season combinations where the sum of attempts is at least 50. Then, we sort the rows descending by `completion_percentage` and report the first 40 values. This is all done in one code chunk.

In [16]:
NFL_spark_ss.filter(col("sum(attempts)") >= 50) \
            .sort(NFL_spark_ss.completion_percentage, ascending = False) \
            .show(40)

+-------------------+------+----------------+------------------+-------------+------------------+------------------+------------------+----------------+-------------------+------------------+-------------------+---------------------+------------------+
|player_display_name|season|sum(completions)|  avg(completions)|sum(attempts)|     avg(attempts)|sum(passing_yards)|avg(passing_yards)|sum(passing_tds)|   avg(passing_tds)|sum(interceptions)| avg(interceptions)|completion_percentage|      td_int_ratio|
+-------------------+------+----------------+------------------+-------------+------------------+------------------+------------------+----------------+-------------------+------------------+-------------------+---------------------+------------------+
|      C.J. Beathard|  2023|              40| 6.666666666666667|           53| 8.833333333333334|             349.0|58.166666666666664|               1|0.16666666666666666|               0.0|                0.0|   0.7547169811320755|              NULL|
|         Colt McCoy|  2021|              74|10.571428571428571|           99|14.142857142857142|             740.0|105.71428571428571|               3|0.42857142857142855|               1.0|0.14285714285714285|   0.7474747474747475|               3.0|
|        Matt Schaub|  2019|              50|              10.0|           67|              13.4|             580.0|             116.0|               3|                0.6|               1.0|                0.2|    0.746268656716418|               3.0|
|         Drew Brees|  2018|             364|24.266666666666666|          489|              32.6|            3992.0| 266.1333333333333|              32| 2.1333333333333333|               5.0| 0.3333333333333333|   0.7443762781186094|               6.4|
|         Drew Brees|  2019|             281|25.545454545454547|          378| 34.36363636363637|            2979.0| 270.8181818181818|              27| 2.4545454545454546|               4.0|0.36363636363636365|   0.7433862433862434|              6.75|
|      Mason Rudolph|  2023|              55|             13.75|           74|              18.5|             719.0|            179.75|               3|               0.75|               0.0|                0.0|   0.7432432432432432|              NULL|
|        Taysom Hill|  2020|              88|               5.5|          121|            7.5625|             928.0|              58.0|               4|               0.25|               2.0|              0.125|   0.7272727272727273|               2.0|
|         Nick Foles|  2018|             141|              28.2|          195|              39.0|            1413.0|             282.6|               7|                1.4|               4.0|                0.8|   0.7230769230769231|              1.75|
|         Drew Brees|  2017|             386|            24.125|          536|              33.5|            4334.0|           270.875|              23|             1.4375|               8.0|                0.5|   0.7201492537313433|             2.875|
|       Sam Bradford|  2016|             395|26.333333333333332|          552|              36.8|            3877.0|258.46666666666664|              20| 1.3333333333333333|               5.0| 0.3333333333333333|   0.7155797101449275|               4.0|
|         Drew Brees|  2011|             471|           29.4375|          660|             41.25|            5535.0|          345.9375|              46|              2.875|              14.0|              0.875|   0.7136363636363636|3.2857142857142856|
|         Colt McCoy|  2014|              91|              18.2|          128|              25.6|            1057.0|             211.4|               4|                0.8|               3.0|                0.6|            0.7109375|1.3333333333333333|
|      Aaron Rodgers|  2020|             372|             23.25|          526|            32.875|            4299.0|          268.6875|              48|                3.0|               5.0|             0.3125|   0.7072243346007605|               9.6|
|       Bailey Zappe|  2022|              65|             16.25|           92|              23.0|             781.0|            195.25|               5|               1.25|               3.0|               0.75|   0.7065217391304348|1.6666666666666667|
|         Drew Brees|  2009|             363|              24.2|          514|34.266666666666666|            4388.0|292.53333333333336|              34| 2.2666666666666666|              11.0| 0.7333333333333333|   0.7062256809338522| 3.090909090909091|
|         Drew Brees|  2020|             275|22.916666666666668|          390|              32.5|            2942.0|245.16666666666666|              24|                2.0|               6.0|                0.5|   0.7051282051282052|               4.0|
|         Joe Burrow|  2021|             366|            22.875|          520|              32.5|            4611.0|          288.1875|              34|              2.125|              14.0|              0.875|   0.7038461538461539|2.4285714285714284|
|         Derek Carr|  2019|             361|           22.5625|          513|           32.0625|            4054.0|           253.375|              21|             1.3125|               8.0|                0.5|   0.7037037037037037|             2.625|
|      Jake Browning|  2023|             171|              19.0|          243|              27.0|            1936.0|215.11111111111111|              12| 1.3333333333333333|               7.0| 0.7777777777777778|   0.7037037037037037|1.7142857142857142|
|       Chase Daniel|  2019|              45|              15.0|           64|21.333333333333332|             435.0|             145.0|               3|                1.0|               2.0| 0.6666666666666666|             0.703125|               1.5|
|     Ryan Tannehill|  2019|             201|             16.75|          286|23.833333333333332|            2742.0|             228.5|              22| 1.8333333333333333|               6.0|                0.5|   0.7027972027972028|3.6666666666666665|
|     Deshaun Watson|  2020|             382|            23.875|          544|              34.0|            4823.0|          301.4375|              33|             2.0625|               7.0|             0.4375|   0.7022058823529411| 4.714285714285714|
|         Alex Smith|  2012|             153|              15.3|          218|              21.8|            1737.0|             173.7|              13|                1.3|               5.0|                0.5|   0.7018348623853211|               2.6|
|       Kirk Cousins|  2018|             425|           26.5625|          606|            37.875|            4298.0|           268.625|              30|              1.875|              10.0|              0.625|   0.7013201320132013|               3.0|
|       Jamie Martin|  2005|             124|              15.5|          177|            22.125|            1277.0|           159.625|               5|              0.625|               7.0|              0.875|   0.7005649717514124|0.7142857142857143|
|         Drew Brees|  2016|             471|           29.4375|          673|           42.0625|            5208.0|             325.5|              37|             2.3125|              15.0|             0.9375|   0.6998514115898959| 2.466666666666667|
|          Tony Romo|  2014|             304|20.266666666666666|          435|              29.0|            3705.0|             247.0|              34| 2.2666666666666666|               9.0|                0.6|   0.6988505747126437|3.7777777777777777|
|          Matt Ryan|  2016|             373|           23.3125|          534|            33.375|            4944.0|             309.0|              38|              2.375|               7.0|             0.4375|   0.6985018726591761| 5.428571428571429|
|       Kirk Cousins|  2015|             379|           23.6875|          543|           33.9375|            4166.0|           260.375|              29|             1.8125|              11.0|             0.6875|   0.6979742173112339|2.6363636363636362|
|         Geno Smith|  2022|             399|23.470588235294116|          572| 33.64705882352941|            4282.0|251.88235294117646|              30| 1.7647058823529411|              11.0| 0.6470588235294118|   0.6975524475524476| 2.727272727272727|
|       Chase Daniel|  2018|              53|             13.25|           76|              19.0|             515.0|            128.75|               3|               0.75|               2.0|                0.5|   0.6973684210526315|               1.5|
|       Carson Wentz|  2018|             279|25.363636363636363|          401| 36.45454545454545|            3074.0|279.45454545454544|              21| 1.9090909090909092|               7.0| 0.6363636363636364|   0.6957605985037406|               3.0|
|       Dak Prescott|  2023|             410| 24.11764705882353|          590|34.705882352941174|            4516.0| 265.6470588235294|              36| 2.1176470588235294|               9.0| 0.5294117647058824|   0.6949152542372882|               4.0|
|      Philip Rivers|  2013|             378|            23.625|          544|              34.0|            4478.0|           279.875|              32|                2.0|              11.0|             0.6875|   0.6948529411764706| 2.909090909090909|
|          Tony Romo|  2010|             148|24.666666666666668|          213|              35.5|            1605.0|             267.5|              11| 1.8333333333333333|               7.0| 1.1666666666666667|   0.6948356807511737|1.5714285714285714|
|       Kirk Cousins|  2023|             216|              27.0|          311|            38.875|            2331.0|           291.375|              18|               2.25|               5.0|              0.625|   0.6945337620578779|               3.6|
|          Matt Ryan|  2018|             422|            26.375|          608|              38.0|            4924.0|            307.75|              35|             2.1875|               7.0|             0.4375|    0.694078947368421|               5.0|
|        Brock Purdy|  2023|             308|             19.25|          444|             27.75|            4280.0|             267.5|              31|             1.9375|              11.0|             0.6875|   0.6936936936936937|2.8181818181818183|
|          Jim Sorgi|  2005|              43|               8.6|           62|              12.4|             444.0|              88.8|               3|                0.6|               1.0|                0.2|   0.6935483870967742|               3.0|
|     Brandon Weeden|  2015|              97|16.166666666666668|          140|23.333333333333332|            1043.0|173.83333333333334|               5| 0.8333333333333334|               2.0| 0.3333333333333333|   0.6928571428571428|               2.5|
+-------------------+------+----------------+------------------+-------------+------------------+------------------+------------------+----------------+-------------------+------------------+-------------------+---------------------+------------------+
only showing top 40 rows

Finally, we show `NFL_spark_ss` subsetted to only include player/season combinations where the sum of attempts is at least 50. Then, we sort the rows descending by `td_int_ratio` and report the first 40 values. This is all done in one code chunk.

In [17]:
NFL_spark_ss.filter(col("sum(attempts)") >= 50) \
            .sort(NFL_spark_ss.td_int_ratio, ascending = False) \
            .show(40)

+-------------------+------+----------------+------------------+-------------+------------------+------------------+------------------+----------------+------------------+------------------+-------------------+---------------------+-----------------+
|player_display_name|season|sum(completions)|  avg(completions)|sum(attempts)|     avg(attempts)|sum(passing_yards)|avg(passing_yards)|sum(passing_tds)|  avg(passing_tds)|sum(interceptions)| avg(interceptions)|completion_percentage|     td_int_ratio|
+-------------------+------+----------------+------------------+-------------+------------------+------------------+------------------+----------------+------------------+------------------+-------------------+---------------------+-----------------+
|          Tom Brady|  2016|             291|             24.25|          432|              36.0|            3554.0| 296.1666666666667|              28|2.3333333333333335|               2.0|0.16666666666666666|   0.6736111111111112|             14.0|
|         Nick Foles|  2013|             203|15.615384615384615|          317|24.384615384615383|            2891.0| 222.3846153846154|              27| 2.076923076923077|               2.0|0.15384615384615385|   0.6403785488958991|             13.5|
|        Josh McCown|  2013|             149|            18.625|          224|              28.0|            1829.0|           228.625|              13|             1.625|               1.0|              0.125|   0.6651785714285714|             13.0|
|      Aaron Rodgers|  2018|             372|             23.25|          597|           37.3125|            4442.0|           277.625|              25|            1.5625|               2.0|              0.125|   0.6231155778894473|             12.5|
|        Damon Huard|  2006|             148|              14.8|          244|              24.4|            1878.0|             187.8|              11|               1.1|               1.0|                0.1|   0.6065573770491803|             11.0|
|      Aaron Rodgers|  2020|             372|             23.25|          526|            32.875|            4299.0|          268.6875|              48|               3.0|               5.0|             0.3125|   0.7072243346007605|              9.6|
|      Aaron Rodgers|  2021|             366|            22.875|          531|           33.1875|            4115.0|          257.1875|              37|            2.3125|               4.0|               0.25|   0.6892655367231638|             9.25|
|          Tom Brady|  2010|             324|             20.25|          492|             30.75|            3900.0|            243.75|              36|              2.25|               4.0|               0.25|   0.6585365853658537|              9.0|
|      Jake Delhomme|  2007|              55|18.333333333333332|           86|28.666666666666668|             617.0|205.66666666666666|               8|2.6666666666666665|               1.0| 0.3333333333333333|   0.6395348837209303|              8.0|
|      Aaron Rodgers|  2014|             341|           21.3125|          520|              32.5|            4381.0|          273.8125|              38|             2.375|               5.0|             0.3125|   0.6557692307692308|              7.6|
|      Aaron Rodgers|  2011|             342|              22.8|          501|              33.4|            4636.0|309.06666666666666|              45|               3.0|               6.0|                0.4|   0.6826347305389222|              7.5|
|         Drew Brees|  2019|             281|25.545454545454547|          378| 34.36363636363637|            2979.0| 270.8181818181818|              27|2.4545454545454546|               4.0|0.36363636363636365|   0.7433862433862434|             6.75|
|      Aaron Rodgers|  2019|             353|           22.0625|          569|           35.5625|            4002.0|           250.125|              26|             1.625|               4.0|               0.25|   0.6203866432337434|              6.5|
|         Drew Brees|  2018|             364|24.266666666666666|          489|              32.6|            3992.0| 266.1333333333333|              32|2.1333333333333333|               5.0| 0.3333333333333333|   0.7443762781186094|              6.4|
|    Patrick Mahomes|  2020|             390|              26.0|          588|              39.2|            4740.0|             316.0|              38| 2.533333333333333|               6.0|                0.4|   0.6632653061224489|6.333333333333333|
|          Tom Brady|  2007|             398|            24.875|          578|            36.125|            4806.0|           300.375|              50|             3.125|               8.0|                0.5|   0.6885813148788927|             6.25|
|     Russell Wilson|  2019|             341|           21.3125|          516|             32.25|            4110.0|           256.875|              31|            1.9375|               5.0|             0.3125|   0.6608527131782945|              6.2|
|      David Garrard|  2007|             208|17.333333333333332|          325|27.083333333333332|            2509.0|209.08333333333334|              18|               1.5|               3.0|               0.25|                 0.64|              6.0|
|   Matthew Stafford|  2010|              57|             14.25|           96|              24.0|             535.0|            133.75|               6|               1.5|               1.0|               0.25|              0.59375|              6.0|
|      Lamar Jackson|  2019|             265|17.666666666666668|          401|26.733333333333334|            3127.0|208.46666666666667|              36|               2.4|               6.0|                0.4|   0.6608478802992519|              6.0|
|       Dak Prescott|  2016|             311|           19.4375|          459|           28.6875|            3667.0|          229.1875|              23|            1.4375|               4.0|               0.25|   0.6775599128540305|             5.75|
|      Aaron Rodgers|  2016|             401|           25.0625|          610|            38.125|            4428.0|            276.75|              40|               2.5|               7.0|             0.4375|   0.6573770491803279|5.714285714285714|
|     Peyton Manning|  2013|             450|            28.125|          659|           41.1875|            5477.0|          342.3125|              55|            3.4375|              10.0|              0.625|   0.6828528072837633|              5.5|
|          Matt Ryan|  2016|             373|           23.3125|          534|            33.375|            4944.0|             309.0|              38|             2.375|               7.0|             0.4375|   0.6985018726591761|5.428571428571429|
|    Patrick Mahomes|  2019|             319|22.785714285714285|          484| 34.57142857142857|            4031.0|287.92857142857144|              26|1.8571428571428572|               5.0|0.35714285714285715|   0.6590909090909091|              5.2|
|         Alex Smith|  2017|             341|22.733333333333334|          505|33.666666666666664|            4042.0|269.46666666666664|              26|1.7333333333333334|               5.0| 0.3333333333333333|   0.6752475247524753|              5.2|
|          Tom Brady|  2015|             402|            25.125|          624|              39.0|            4770.0|           298.125|              36|              2.25|               7.0|             0.4375|   0.6442307692307693|5.142857142857143|
|        Jeff Garcia|  2006|             116|              14.5|          188|              23.5|            1309.0|           163.625|              10|              1.25|               2.0|               0.25|   0.6170212765957447|              5.0|
|          Matt Ryan|  2018|             422|            26.375|          608|              38.0|            4924.0|            307.75|              35|            2.1875|               7.0|             0.4375|    0.694078947368421|              5.0|
|     Russell Wilson|  2018|             280|              17.5|          427|           26.6875|            3448.0|             215.5|              35|            2.1875|               7.0|             0.4375|   0.6557377049180327|              5.0|
|         Geno Smith|  2021|              65|             16.25|           95|             23.75|             702.0|             175.5|               5|              1.25|               1.0|               0.25|   0.6842105263157895|              5.0|
|      Aaron Rodgers|  2012|             371|           23.1875|          552|              34.5|            4295.0|          268.4375|              39|            2.4375|               8.0|                0.5|   0.6721014492753623|            4.875|
|     Ryan Tannehill|  2020|             315|           19.6875|          481|           30.0625|            3819.0|          238.6875|              34|             2.125|               7.0|             0.4375|   0.6548856548856549|4.857142857142857|
|        Brett Favre|  2009|             364|             22.75|          532|             33.25|            4202.0|           262.625|              33|            2.0625|               7.0|             0.4375|   0.6842105263157895|4.714285714285714|
|       Kirk Cousins|  2021|             372|             23.25|          561|           35.0625|            4221.0|          263.8125|              33|            2.0625|               7.0|             0.4375|   0.6631016042780749|4.714285714285714|
|       Carson Wentz|  2017|             265|20.384615384615383|          440| 33.84615384615385|            3296.0|253.53846153846155|              33|2.5384615384615383|               7.0| 0.5384615384615384|   0.6022727272727273|4.714285714285714|
|     Deshaun Watson|  2020|             382|            23.875|          544|              34.0|            4823.0|          301.4375|              33|            2.0625|               7.0|             0.4375|   0.7022058823529411|4.714285714285714|
|         Derek Carr|  2016|             357|              23.8|          560|37.333333333333336|            3937.0|262.46666666666664|              28|1.8666666666666667|               6.0|                0.4|               0.6375|4.666666666666667|
|     Jameis Winston|  2021|              95|13.571428571428571|          161|              23.0|            1170.0|167.14285714285714|              14|               2.0|               3.0|0.42857142857142855|   0.5900621118012422|4.666666666666667|
|        C.J. Stroud|  2023|             319|21.266666666666666|          499|33.266666666666666|            4108.0| 273.8666666666667|              23|1.5333333333333334|               5.0| 0.3333333333333333|   0.6392785571142284|              4.6|
+-------------------+------+----------------+------------------+-------------+------------------+------------------+------------------+----------------+------------------+------------------+-------------------+---------------------+-----------------+
only showing top 40 rows