# **ST 554 Final Project**
---
Authored by: Jamie Loring

Collaborator: Dr. Justin Post (code from lecture videos & slides)

## **Setup**

The code below imports the required modules that are needed for this project.

In [1]:
import pandas as pd
import numpy as np
from pyspark.sql import SparkSession
from pyspark.ml.feature import SQLTransformer, StringIndexer, Binarizer, VectorAssembler, OneHotEncoder, PCA, \
                               StandardScaler
from pyspark.ml.regression import LinearRegression
from pyspark.ml.tuning import CrossValidator, ParamGridBuilder
from pyspark.ml.evaluation import RegressionEvaluator
from pyspark.sql.functions import col
from pyspark.ml import Pipeline

#from sklearn import linear_model
#from math import sqrt
#from sklearn.model_selection import train_test_split, cross_validate
#from sklearn.metrics import mean_squared_error, mean_absolute_error, log_loss, accuracy_score
#from sklearn.linear_model import LinearRegression, LogisticRegression, Lasso, Ridge, ElasticNet, \
                                 #LogisticRegressionCV, LassoCV, RidgeCV, ElasticNetCV
#from sklearn.preprocessing import PolynomialFeatures

#from sklearn.tree import DecisionTreeRegressor, plot_tree, DecisionTreeClassifier
#from sklearn.model_selection import GridSearchCV
#from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
#from sklearn.neighbors import KNeighborsRegressor, KNeighborsClassifier

The code below sets up our `spark` object and only allows errors to print out in the future (i.e., it suppresses warnings).

In [2]:
spark = SparkSession.builder.master('local[*]').appName('my_app').getOrCreate()
spark.sparkContext.setLogLevel("ERROR")

WARNING: Using incubator modules: jdk.incubator.vector
Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
26/04/27 16:28:35 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
26/04/27 16:28:35 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
26/04/27 16:28:35 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
26/04/27 16:28:35 WARN Utils: Service 'SparkUI' could not bind on port 4042. Attempting port 4043.

The code below reads in the `power_ml_data.csv` file from the provided URL using `pandas`.

In [3]:
power_data = pd.read_csv("https://www4.stat.ncsu.edu/~online/datasets/power_ml_data.csv")
power_data.head()

,Temperature,Humidity,Wind_Speed,General_Diffuse_Flows,Diffuse_Flows,Power_Zone_1,Power_Zone_2,Power_Zone_3,Month,Hour
0,6.559,73.8,0.083,0.051,0.119,34055.69620,16128.87538,20240.96386,1,0
1,6.414,74.5,0.083,0.070,0.085,29814.68354,19375.07599,20131.08434,1,0
2,6.313,74.5,0.080,0.062,0.100,29128.10127,19006.68693,19668.43373,1,0
3,6.121,75.0,0.083,0.091,0.096,28228.86076,18361.09422,18899.27711,1,0
4,5.921,75.7,0.081,0.048,0.085,27335.69620,17872.34043,18442.40964,1,0

Now, we convert our `pandas dataframe` to a `spark` SQL style dataframe. This new object will be called `power_ML`. For better readability, throughout this project, I will display results using `.toPandas()` and `.head()` rather than `.show()`. It is important to note that this choice does not change `power_ML` back to a `pandas` or `pandas-on-spark` dataframe; rather, it just changes the way it is *displayed*.

In [5]:
power_ML = spark.createDataFrame(power_data)
power_ML.toPandas().head()

,Temperature,Humidity,Wind_Speed,General_Diffuse_Flows,Diffuse_Flows,Power_Zone_1,Power_Zone_2,Power_Zone_3,Month,Hour
0,6.559,73.8,0.083,0.051,0.119,34055.69620,16128.87538,20240.96386,1,0
1,6.414,74.5,0.083,0.070,0.085,29814.68354,19375.07599,20131.08434,1,0
2,6.313,74.5,0.080,0.062,0.100,29128.10127,19006.68693,19668.43373,1,0
3,6.121,75.0,0.083,0.091,0.096,28228.86076,18361.09422,18899.27711,1,0
4,5.921,75.7,0.081,0.048,0.085,27335.69620,17872.34043,18442.40964,1,0

We are going to treat the `Power_Zone_3` variable as our response variable. We want to imagine that we know that the `Power_Zone_3` reading is going to go offline in the future, and we need to be able to predict that value appropriately using the other variables in the dataset.

## **Fitting the Model**

We are going to fit an elastic net model using CV without a training & testing split. Before we can fit our model, we have to perform the required transformations using `MLlib` functions. All (nested) transformations will be saved as objects so 1) We can display our progress through the transformations and 2) We can check to make sure we do not miss any transformations in the final pipeline.

First, we need to check to see how the `Hour` column is stored.

In [6]:
power_ML.dtypes

[('Temperature', 'double'),
 ('Humidity', 'double'),
 ('Wind_Speed', 'double'),
 ('General_Diffuse_Flows', 'double'),
 ('Diffuse_Flows', 'double'),
 ('Power_Zone_1', 'double'),
 ('Power_Zone_2', 'double'),
 ('Power_Zone_3', 'double'),
 ('Month', 'bigint'),
 ('Hour', 'bigint')]

Now that we have confirmed that it's not a `DoubleType`, we will need to use an SQL transformer to cast the `Hour` variable as a `DoubleType`.

In [7]:
cast_hour = SQLTransformer(
    statement = """
                SELECT *, CAST(Hour as DOUBLE) as Hour_Double_Type FROM __THIS__
                """
            )

tf_1 = cast_hour.transform(power_ML)
tf_1.toPandas().head()

,Temperature,Humidity,Wind_Speed,General_Diffuse_Flows,Diffuse_Flows,Power_Zone_1,Power_Zone_2,Power_Zone_3,Month,Hour,Hour_Double_Type
0,6.559,73.8,0.083,0.051,0.119,34055.69620,16128.87538,20240.96386,1,0,0.0
1,6.414,74.5,0.083,0.070,0.085,29814.68354,19375.07599,20131.08434,1,0,0.0
2,6.313,74.5,0.080,0.062,0.100,29128.10127,19006.68693,19668.43373,1,0,0.0
3,6.121,75.0,0.083,0.091,0.096,28228.86076,18361.09422,18899.27711,1,0,0.0
4,5.921,75.7,0.081,0.048,0.085,27335.69620,17872.34043,18442.40964,1,0,0.0

Next, we need to binarize the updated `Hour_Double_Type` column based on it being less than 6.5 or not. We are essentially creating a night vs. day variable.

In [8]:
binarize_hour = Binarizer(threshold = 6.5, inputCol = "Hour_Double_Type", outputCol = "Night_vs_Day")

tf_2 = binarize_hour.transform(tf_1)
tf_2.toPandas().head()

,Temperature,Humidity,Wind_Speed,General_Diffuse_Flows,Diffuse_Flows,Power_Zone_1,Power_Zone_2,Power_Zone_3,Month,Hour,Hour_Double_Type,Night_vs_Day
0,6.559,73.8,0.083,0.051,0.119,34055.69620,16128.87538,20240.96386,1,0,0.0,0.0
1,6.414,74.5,0.083,0.070,0.085,29814.68354,19375.07599,20131.08434,1,0,0.0,0.0
2,6.313,74.5,0.080,0.062,0.100,29128.10127,19006.68693,19668.43373,1,0,0.0,0.0
3,6.121,75.0,0.083,0.091,0.096,28228.86076,18361.09422,18899.27711,1,0,0.0,0.0
4,5.921,75.7,0.081,0.048,0.085,27335.69620,17872.34043,18442.40964,1,0,0.0,0.0

Continuing on, we need to one-hot encode the `Month` variable. Since `Month` is already an integer, we do _**not**_ need to use `StringIndexer()`.

In [10]:
encoder_OHE = OneHotEncoder(inputCols = ["Month"], outputCols = ["Month_OHE"])
model_OHE = encoder_OHE.fit(tf_2)

tf_3 = model_OHE.transform(tf_2)
tf_3.toPandas().head()

,Temperature,Humidity,Wind_Speed,General_Diffuse_Flows,Diffuse_Flows,Power_Zone_1,Power_Zone_2,Power_Zone_3,Month,Hour,Hour_Double_Type,Night_vs_Day,Month_OHE
0,6.559,73.8,0.083,0.051,0.119,34055.69620,16128.87538,20240.96386,1,0,0.0,0.0,"(0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
1,6.414,74.5,0.083,0.070,0.085,29814.68354,19375.07599,20131.08434,1,0,0.0,0.0,"(0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
2,6.313,74.5,0.080,0.062,0.100,29128.10127,19006.68693,19668.43373,1,0,0.0,0.0,"(0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
3,6.121,75.0,0.083,0.091,0.096,28228.86076,18361.09422,18899.27711,1,0,0.0,0.0,"(0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
4,5.921,75.7,0.081,0.048,0.085,27335.69620,17872.34043,18442.40964,1,0,0.0,0.0,"(0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."

Our next step is to run a PCA fit on the following variables:
- `Temperature`
- `Humidity`
- `Wind_Speed`
- `General_Diffuse_Flows`
- `Diffuse_Flows`

We will also need to standarize our predictors using `StandardScaler()`.

**Note:** This will be a multi-step process, outlined with in-line comments in the code chunk below.

In [12]:
# use VectorAssembler() to place the above variables in a column together for use with the PCA() estimator
assembler_PCA = VectorAssembler(
                inputCols = ["Temperature", "Humidity", "Wind_Speed",
                             "General_Diffuse_Flows", "Diffuse_Flows"],
                outputCol = "features_for_PCA",
                handleInvalid = "keep"
             )

# update transformations
tf_4 = assembler_PCA.transform(tf_3)

# use StandardScaler() to standardize predictors
scaler_PCA = StandardScaler(inputCol = "features_for_PCA", outputCol = "features_for_PCA_scaled",
                            withStd = True, withMean = True)
# fit scaler_PCA
scaler_fit = scaler_PCA.fit(tf_4)

# update transformations
tf_5 = scaler_fit.transform(tf_4)

# run PCA, using 2 PC's in the transformation
PCA_func = PCA(k = 2, inputCol = "features_for_PCA_scaled", outputCol = "PCA_features_scaled")

# fit the PCA model
PCA_model = PCA_func.fit(tf_5)

# update transformations
tf_6 = PCA_model.transform(tf_5)

# show updated transformations
tf_6.toPandas().head()

,Temperature,Humidity,Wind_Speed,General_Diffuse_Flows,Diffuse_Flows,Power_Zone_1,Power_Zone_2,Power_Zone_3,Month,Hour,Hour_Double_Type,Night_vs_Day,Month_OHE,features_for_PCA,features_for_PCA_scaled,PCA_features_scaled
0,6.559,73.8,0.083,0.051,0.119,34055.69620,16128.87538,20240.96386,1,0,0.0,0.0,"(0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[6.559, 73.8, 0.083, 0.051, 0.119]","[-2.1079477438809433, 0.3542085264292604, -0.7...","[2.0690743213463723, 0.8078678829472257]"
1,6.414,74.5,0.083,0.070,0.085,29814.68354,19375.07599,20131.08434,1,0,0.0,0.0,"(0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[6.414, 74.5, 0.083, 0.07, 0.085]","[-2.1328903699941857, 0.3991947174962608, -0.7...","[2.1029210638806544, 0.8152476222806385]"
2,6.313,74.5,0.080,0.062,0.100,29128.10127,19006.68693,19668.43373,1,0,0.0,0.0,"(0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[6.313, 74.5, 0.08, 0.062, 0.1]","[-2.1502641992178924, 0.3991947174962608, -0.8...","[2.1120662633791016, 0.8227151924829952]"
3,6.121,75.0,0.083,0.091,0.096,28228.86076,18361.09422,18899.27711,1,0,0.0,0.0,"(0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[6.121, 75.0, 0.083, 0.091, 0.096]","[-2.183291676554047, 0.4313277111155467, -0.79...","[2.14350318474222, 0.8329135817940956]"
4,5.921,75.7,0.081,0.048,0.085,27335.69620,17872.34043,18442.40964,1,0,0.0,0.0,"(0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[5.921, 75.7, 0.081, 0.048, 0.085]","[-2.217695298779209, 0.47631390218254716, -0.8...","[2.182444003662701, 0.8444681624812326]"

We now need to put our model predictors into a single column called features. We can do this with `VectorAssembler()`. We will also use `StandardScaler()` to standardize our features. Since `PCA_features_scaled` has already been standardized, we do not need to re-standardize it, so this will be a multi-step process.

In [13]:
# assemble features vector without PCA for scaling
assembler_features = VectorAssembler(
                          inputCols = ["Night_vs_Day", "Power_Zone_1",
                                       "Power_Zone_2", "Month_OHE"],
                          outputCol = "features_pre_scale",
                          handleInvalid = "keep"
                    )

# update transformations
tf_7 = assembler_features.transform(tf_6)

# use StandardScaler() to standardize features -- remember PCA_features_scaled is already standardized!
scaler_features = StandardScaler(inputCol = "features_pre_scale", outputCol = "features_scaled",
                                 withStd = True, withMean = True)

# fit scaler_features
scaler_fit_feat = scaler_features.fit(tf_7)

# update transformations
tf_8 = scaler_fit_feat.transform(tf_7)

# use VectorAssembler() again to combine PCA_features_scaled and features_scaled into one features column
assembler_features_final = VectorAssembler(
                                inputCols = ["PCA_features_scaled", "features_scaled"],
                                outputCol = "features",
                                handleInvalid = "keep"
                        )

# update transformations
tf_9 = assembler_features_final.transform(tf_8)

# show updated transformations
tf_9.toPandas().head()

,Temperature,Humidity,Wind_Speed,General_Diffuse_Flows,Diffuse_Flows,Power_Zone_1,Power_Zone_2,Power_Zone_3,Month,Hour,Hour_Double_Type,Night_vs_Day,Month_OHE,features_for_PCA,features_for_PCA_scaled,PCA_features_scaled,features_pre_scale,features_scaled,features
0,6.559,73.8,0.083,0.051,0.119,34055.69620,16128.87538,20240.96386,1,0,0.0,0.0,"(0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[6.559, 73.8, 0.083, 0.051, 0.119]","[-2.1079477438809433, 0.3542085264292604, -0.7...","[2.0690743213463723, 0.8078678829472257]","(0.0, 34055.6962, 16128.87538, 0.0, 1.0, 0.0, ...","[-1.5544690531019132, 0.24130775579578978, -0....","[2.0690743213463723, 0.8078678829472257, -1.55..."
1,6.414,74.5,0.083,0.070,0.085,29814.68354,19375.07599,20131.08434,1,0,0.0,0.0,"(0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[6.414, 74.5, 0.083, 0.07, 0.085]","[-2.1328903699941857, 0.3991947174962608, -0.7...","[2.1029210638806544, 0.8152476222806385]","(0.0, 29814.68354, 19375.07599, 0.0, 1.0, 0.0,...","[-1.5544690531019132, -0.35350356900601565, -0...","[2.1029210638806544, 0.8152476222806385, -1.55..."
2,6.313,74.5,0.080,0.062,0.100,29128.10127,19006.68693,19668.43373,1,0,0.0,0.0,"(0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[6.313, 74.5, 0.08, 0.062, 0.1]","[-2.1502641992178924, 0.3991947174962608, -0.8...","[2.1120662633791016, 0.8227151924829952]","(0.0, 29128.10127, 19006.68693, 0.0, 1.0, 0.0,...","[-1.5544690531019132, -0.449798237837335, -0.3...","[2.1120662633791016, 0.8227151924829952, -1.55..."
3,6.121,75.0,0.083,0.091,0.096,28228.86076,18361.09422,18899.27711,1,0,0.0,0.0,"(0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[6.121, 75.0, 0.083, 0.091, 0.096]","[-2.183291676554047, 0.4313277111155467, -0.79...","[2.14350318474222, 0.8329135817940956]","(0.0, 28228.86076, 18361.09422, 0.0, 1.0, 0.0,...","[-1.5544690531019132, -0.5759186911227896, -0....","[2.14350318474222, 0.8329135817940956, -1.5544..."
4,5.921,75.7,0.081,0.048,0.085,27335.69620,17872.34043,18442.40964,1,0,0.0,0.0,"(0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[5.921, 75.7, 0.081, 0.048, 0.085]","[-2.217695298779209, 0.47631390218254716, -0.8...","[2.182444003662701, 0.8444681624812326]","(0.0, 27335.6962, 17872.34043, 0.0, 1.0, 0.0, ...","[-1.5544690531019132, -0.7011869790980542, -0....","[2.182444003662701, 0.8444681624812326, -1.554..."

Finally, we rename the response variable, `Power_Zone_3`, as `label`. We will also use the SQL transformer to select the `features` vector that was created in the previous step.

In [14]:
label_and_features = SQLTransformer(
    statement = """
                SELECT features, Power_Zone_3 as label FROM __THIS__
                """
            )

# update transformations
tf_10 = label_and_features.transform(tf_9)
tf_10.toPandas().head()

                                            features        label
0  [2.0690743213463723, 0.8078678829472257, -1.55...  20240.96386
1  [2.1029210638806544, 0.8152476222806385, -1.55...  20131.08434
2  [2.1120662633791016, 0.8227151924829952, -1.55...  19668.43373
3  [2.14350318474222, 0.8329135817940956, -1.5544...  18899.27711
4  [2.182444003662701, 0.8444681624812326, -1.554...  18442.40964

We can now put all of our transformations into the pipeline. We will have 10 of them, plus our linear regression instance. They are:
- `cast_hour`
- `binarize_hour`
- `encoder_OHE`
- `assembler_PCA`
- `scaler_PCA`
- `PCA_func`
- `assembler_features`
- `scaler_features`
- `assembler_features_final`
- `label_and_features`
- and `lr`, which will be the instance of our `LinearRegression()`

**Note:** Only the transformers and estimators need to be put into the pipeline since the pipeline will automatically handle which ones need to be fit. The fit objects up to this point were only created to show the progress of the transformations and check their functionality, but they themselves do not go into the pipeline!

*Example:* `encoder_OHE` *goes into the pipeline rather than* `model_OHE`

In [15]:
lr = LinearRegression()
pipeline = Pipeline(stages = [cast_hour, binarize_hour, encoder_OHE, assembler_PCA,
                              scaler_PCA, PCA_func, assembler_features, scaler_features,
                              assembler_features_final, label_and_features, lr])

We are now ready to fit our elastic net model. We are provided with the following grid for `regParam` and `elasticNetParam`:
- `regParam`: 0, 0.05, 0.1, 0.25, 0.5, 0.75, 0.9, 0.95, 0.98, 0.99, 1
- `elasticNetParam`: 0, 0.05, 0.1, 0.25, 0.5, 0.75, 0.9, 0.95, 0.98, 0.99, 1

Since our `pipeline` object is already set up, we have the following remaining steps to complete in creating our model:
- build the parameter grid
- use cross-validation (5 folds) to choose the best combination of parameters using RMSE
- fit the model

**Note:** The use of `parallelism = 128` in `CrossValidator()` speeds up the runtime from about 12 minutes to about 6 minutes! Please be patient! Additionally, the red line that appears under the code chunk is *not* representative of an actual error, but rather staging outputs from the log.

In [30]:
# build parameter grid
paramGrid = ParamGridBuilder() \
            .addGrid(lr.regParam, [0, 0.05, 0.1, 0.25, 0.5, 0.75, 0.9, 0.95, 0.98, 0.99, 1]) \
            .addGrid(lr.elasticNetParam, [0, 0.05, 0.1, 0.25, 0.5, 0.75, 0.9, 0.95, 0.98, 0.99, 1]) \
            .build()


# set up cross validation with pipeline
crossval = CrossValidator(estimator = pipeline,
                          estimatorParamMaps = paramGrid,
                          evaluator = RegressionEvaluator(metricName = 'rmse'),
                          numFolds = 5,
                          seed = 44,
                          parallelism = 128)

# fit the model using cross-validation to choose the best model
cvModel = crossval.fit(power_ML)

Although the `.bestModel` attribute will store the best model as a result of cross-validation by default, we want to look to see what model is the best. The code below prints the RMSE for the model fit with its corresponding parameters, `regParam` and `elasticNetParam`. I then sort this output in ascending order so we can see the lowest RMSE first (along with its corresponding parameters).

In [17]:
my_list = []

for i in range(len(paramGrid)):
    my_list.append([cvModel.avgMetrics[i], paramGrid[i].values()])
    
my_list.sort(key=lambda x: x[0]) #specifies sorting by avgMetrics rather than the dict_values
my_list

[[2175.025614452874, dict_values([0.25, 0.5])],
 [2175.0335187645323, dict_values([0.5, 0.25])],
 [2175.0335454632104, dict_values([0.5, 0.05])],
 [2175.0341016574052, dict_values([0.5, 0.1])],
 [2175.0349079585444, dict_values([0.05, 0.5])],
 [2175.035462853383, dict_values([0.25, 0.1])],
 [2175.035512165499, dict_values([0.1, 0.95])],
 [2175.035587292835, dict_values([0.05, 0.98])],
 [2175.0356041252753, dict_values([0.05, 0.9])],
 [2175.0356236594253, dict_values([0.05, 0.95])],
 [2175.035731007239, dict_values([0.05, 0.99])],
 [2175.035734665818, dict_values([0.05, 1.0])],
 [2175.035803359566, dict_values([0.05, 0.25])],
 [2175.035833255783, dict_values([0.1, 0.0])],
 [2175.035841619817, dict_values([0.1, 0.1])],
 [2175.0358417832153, dict_values([0.25, 0.0])],
 [2175.035842577646, dict_values([0.05, 0.75])],
 [2175.03585093693, dict_values([0.05, 0.0])],
 [2175.035880590475, dict_values([0.0, 0.98])],
 [2175.0358805904757, dict_values([0.0, 0.25])],
 [2175.035880590477, dict_values([0.0, 0.75])],
 [2175.0358805904775, dict_values([0.0, 0.1])],
 [2175.035880590478, dict_values([0.0, 0.5])],
 [2175.035880590479, dict_values([0.0, 0.9])],
 [2175.035880671125, dict_values([0.0, 0.95])],
 [2175.035880671125, dict_values([0.0, 1.0])],
 [2175.0358806711256, dict_values([0.0, 0.05])],
 [2175.035880754116, dict_values([0.0, 0.0])],
 [2175.0358807541174, dict_values([0.0, 0.99])],
 [2175.035916294112, dict_values([0.25, 0.75])],
 [2175.0359505738693, dict_values([0.1, 0.5])],
 [2175.035956982888, dict_values([0.1, 0.9])],
 [2175.0360219916993, dict_values([0.25, 0.25])],
 [2175.0360607620323, dict_values([0.5, 0.0])],
 [2175.03611611642, dict_values([0.5, 0.9])],
 [2175.0362199346864, dict_values([0.1, 0.75])],
 [2175.036329046605, dict_values([0.25, 0.05])],
 [2175.036533837649, dict_values([0.1, 0.25])],
 [2175.0365348538376, dict_values([0.75, 0.0])],
 [2175.0368004840375, dict_values([0.5, 0.75])],
 [2175.036941359307, dict_values([0.9, 0.0])],
 [2175.037097156441, dict_values([0.95, 0.0])],
 [2175.037195499917, dict_values([0.98, 0.0])],
 [2175.0372010775873, dict_values([0.99, 0.25])],
 [2175.0372290915716, dict_values([0.99, 0.0])],
 [2175.0372313614257, dict_values([0.25, 1.0])],
 [2175.037263088371, dict_values([1.0, 0.0])],
 [2175.0372823652824, dict_values([0.25, 0.95])],
 [2175.037323324621, dict_values([0.25, 0.98])],
 [2175.0373741267863, dict_values([0.25, 0.99])],
 [2175.0374908182152, dict_values([0.98, 0.25])],
 [2175.0375767805435, dict_values([1.0, 0.25])],
 [2175.037612282755, dict_values([0.1, 0.05])],
 [2175.0376550958604, dict_values([0.05, 0.1])],
 [2175.0379456731143, dict_values([0.25, 0.9])],
 [2175.0382580294904, dict_values([0.1, 0.98])],
 [2175.0382593896675, dict_values([0.75, 0.05])],
 [2175.038266419848, dict_values([0.1, 0.99])],
 [2175.0383369951587, dict_values([0.1, 1.0])],
 [2175.0386065482826, dict_values([0.9, 0.05])],
 [2175.03870830048, dict_values([0.95, 0.05])],
 [2175.03897168182, dict_values([0.98, 0.05])],
 [2175.0390185115757, dict_values([0.99, 0.05])],
 [2175.0390551132523, dict_values([1.0, 0.05])],
 [2175.0392088114972, dict_values([0.75, 0.5])],
 [2175.0392710518604, dict_values([0.75, 0.1])],
 [2175.0394349785975, dict_values([1.0, 0.1])],
 [2175.039626674231, dict_values([0.9, 0.1])],
 [2175.039640711996, dict_values([0.05, 0.05])],
 [2175.0397551109854, dict_values([0.75, 0.25])],
 [2175.0398334117212, dict_values([0.99, 0.1])],
 [2175.039870079505, dict_values([0.5, 0.95])],
 [2175.039912937423, dict_values([0.5, 0.5])],
 [2175.040453386412, dict_values([0.5, 0.98])],
 [2175.040575442404, dict_values([0.5, 0.99])],
 [2175.0406294192476, dict_values([0.95, 0.1])],
 [2175.0407546574907, dict_values([0.5, 1.0])],
 [2175.0414055116207, dict_values([0.9, 0.5])],
 [2175.0415166017206, dict_values([0.98, 0.1])],
 [2175.0423579559565, dict_values([0.95, 0.25])],
 [2175.043103048996, dict_values([0.9, 0.25])],
 [2175.044166928811, dict_values([0.95, 0.5])],
 [2175.044218334925, dict_values([0.98, 0.5])],
 [2175.044801968951, dict_values([0.99, 0.5])],
 [2175.0450338852033, dict_values([1.0, 0.5])],
 [2175.045120023714, dict_values([0.75, 0.75])],
 [2175.04899494441, dict_values([0.75, 0.9])],
 [2175.052239986608, dict_values([0.9, 0.75])],
 [2175.0543952876506, dict_values([0.95, 0.75])],
 [2175.055912794986, dict_values([0.98, 0.75])],
 [2175.0594562387196, dict_values([0.75, 0.95])],
 [2175.0597552605486, dict_values([0.75, 0.98])],
 [2175.0600362847335, dict_values([0.75, 0.99])],
 [2175.060347003291, dict_values([0.75, 1.0])],
 [2175.0621536509943, dict_values([0.99, 0.75])],
 [2175.0621980917495, dict_values([1.0, 0.75])],
 [2175.0652220922325, dict_values([0.9, 0.9])],
 [2175.0655652519786, dict_values([0.9, 0.95])],
 [2175.066322446209, dict_values([0.95, 0.9])],
 [2175.0679089168198, dict_values([0.9, 0.99])],
 [2175.068112127061, dict_values([0.9, 1.0])],
 [2175.0689018874004, dict_values([0.95, 0.95])],
 [2175.0691888856163, dict_values([0.98, 0.9])],
 [2175.0693978996596, dict_values([1.0, 0.9])],
 [2175.0694334934346, dict_values([0.9, 0.98])],
 [2175.069542426985, dict_values([0.95, 0.98])],
 [2175.0711549746475, dict_values([0.98, 0.95])],
 [2175.0715265753192, dict_values([0.95, 0.99])],
 [2175.0715843965254, dict_values([0.99, 0.9])],
 [2175.072029017278, dict_values([0.95, 1.0])],
 [2175.0725785552386, dict_values([0.99, 0.95])],
 [2175.072845244698, dict_values([1.0, 0.95])],
 [2175.073311119793, dict_values([0.98, 1.0])],
 [2175.073903414798, dict_values([0.98, 0.98])],
 [2175.0744187940572, dict_values([1.0, 0.98])],
 [2175.074428574316, dict_values([0.99, 0.99])],
 [2175.074540394961, dict_values([0.98, 0.99])],
 [2175.0748796187227, dict_values([0.99, 0.98])],
 [2175.0753988719516, dict_values([0.99, 1.0])],
 [2175.0754543827716, dict_values([1.0, 0.99])],
 [2175.0759315449113, dict_values([1.0, 1.0])]]

Thus, the best multiple linear regression model based on cross-validation with RMSE is one with a regularization parameter of 0.25 and an elastic net parameter of 0.5. This tells us that we have a combination of L1 and L2 penalties; hence, we are fitting an elastic net model! We can now print the intercept and coefficients of this best model, as well as the CV error (with its corresponding tuning parameters).

In [18]:
# need to use indexing since the model is the last stage of the pipeline
print('Intercept:', cvModel.bestModel.stages[-1].intercept)
print('Coefficients (in Features Order):', cvModel.bestModel.stages[-1].coefficients)

print(' ')

print("Best regParam:", cvModel.bestModel.stages[-1]._java_obj.getRegParam())
print("Best elasticNetParam:", cvModel.bestModel.stages[-1]._java_obj.getElasticNetParam())
print('Resulting Best CV RMSE:', round(min(cvModel.avgMetrics), 4))

Intercept: 17831.197607816746
Coefficients (in Features Order): [281.33759408416756,-508.5488523409969,-933.3422279345817,4380.973673101201,582.7712870595075,0.0,1670.6436195006297,1521.0143011644407,1488.0485558207433,1932.6899471239333,1411.9841811335202,1784.2129277383003,3556.7197890829834,2402.836302038806,373.59506055395997,-54.722433929871215,504.5217858788957]

Best regParam: 0.25
Best elasticNetParam: 0.5
Resulting Best CV RMSE: 2175.0256

We now report the training set RMSE, i.e., the RMSE on the full dataset, by using the fitted model as a transformer and evaluating on the entire training (full) dataset.

In [20]:
training_rmse = RegressionEvaluator(metricName = 'rmse').evaluate(cvModel.transform(power_ML))

print('Entire Training (Full) Dataset RMSE:', round(training_rmse, 5))

Entire Training (Full) Dataset RMSE: 2174.44967

The last step is to take the outputted transformations from the model (i.e., the predictions) and create a `residual` column defined as `label` - `prediction`. We will print out a resulting dataframe with the following columns:
- `residual`
- `label`
- `prediction`

In [21]:
# store previous model transformer in an object
tf_final = cvModel.transform(power_ML)

# create residual column
resids_label_preds = tf_final.withColumn("residual", col("label") - col("prediction"))
resids_label_preds.select("residual", "label", "prediction").toPandas()

          residual        label    prediction
0      -695.215712  20240.96386  20936.179572
1      1431.166976  20131.08434  18699.917364
2      1432.893079  19668.43373  18235.540651
3      1284.964277  18899.27711  17614.312833
4      1426.591996  18442.40964  17015.817644
...            ...          ...           ...
47169  2469.850984  14780.31212  12310.461136
47170  2647.362365  14428.81152  11781.449155
47171  2633.732742  13806.48259  11172.749848
47172  2794.162807  13512.60504  10718.442233
47173  3062.851170  13345.49820  10282.647030

[47174 rows x 3 columns]

## **Streaming**
In this part of the project, we will be using the model created in the previous section with streaming data!

### **Reading a Stream**
In my `jupyterhub` main directory, I have created a folder called `csv_files_final`. This folder will be used to read in the stream in the form of `.csv` files.

The code below sets up the schema for the stream by using the schema from the original data as we did in the Homework 10 assignment.

In [22]:
myschema = power_ML.schema
power_stream = spark.readStream.option("header", "true").schema(myschema).csv("csv_files_final")

### **Transformations and Aggregations**

First, with the stream, we use the model transformer to obtain predictions from the incoming data. This can be accomplished by creating an object very similar to `tf_final`. The only difference is that rather than supplying `power_ML` -- our data object -- to the `transform()` method, we will supply the stream object -- `power_stream`. The newly created object will be called `power_transform`, and we can use this to create a `residual` column.

In [23]:
# use model transformer with stream
power_transform = cvModel.transform(power_stream)

# create residual column
pwr_tf_resids = power_transform.withColumn("residual", col("label") - col("prediction")) \
                               .select("residual", "label", "prediction")

Next, we can use the stream again, with another transformation on the original stream, by modifying the response variable (`Power_Zone_3`) to be called `label`. This will be done using the `.withColumnRenamed()` method, rather than an SQL Transformer, because we want to keep all the original variables as well.

In [24]:
label_rename = power_stream.withColumnRenamed("Power_Zone_3", "label")

We can now join the above previous transform with this stream based on the `label` variable. This will be done with an inner join via the `.join()` method.

In [25]:
stream_join = pwr_tf_resids.join(label_rename, "label", "inner")

### **Writing Step**
We are now ready to write the `stream_join`. We will write it to the console using the `append` output mode. The code below will start the query.

In [33]:
query = stream_join.writeStream.outputMode("append").format("console").start()

-------------------------------------------
Batch: 0
-------------------------------------------
+-----------+-------------------+------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|      label|           residual|        prediction|Temperature|Humidity|Wind_Speed|General_Diffuse_Flows|Diffuse_Flows|Power_Zone_1|Power_Zone_2|Month|Hour|
+-----------+-------------------+------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|19633.35423|-2277.2771074885422|21910.631337488543|      26.01|    72.0|     4.919|                588.5|        119.1| 34342.64151| 20923.33685|    8|  10|
|25331.17409| -979.1840641396084| 26310.35815413961|      19.91|    79.8|      4.92|                67.03|         70.6| 44934.29508| 26990.71207|    5|  19|
|16730.05025| 131.37553991079767|16598.674710089203|      16.43|   56.76|     0.082|                722.0|        348.7| 32967.45763| 21592.70517|    2|  13|
|37536.40167|  2144.858399784476| 35391.54327021552|      25.15|    78.7|     4.904|                 0.11|         0.07| 46443.58804| 28545.56962|    7|  21|
|9329.171669| -2369.946626564637|11699.118295564636|      13.15|   60.85|     0.081|                22.17|        22.52| 30606.84411| 25837.37343|   12|  16|
+-----------+-------------------+------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+

-------------------------------------------
Batch: 1
-------------------------------------------
+-----------+-------------------+------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|      label|           residual|        prediction|Temperature|Humidity|Wind_Speed|General_Diffuse_Flows|Diffuse_Flows|Power_Zone_1|Power_Zone_2|Month|Hour|
+-----------+-------------------+------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|16197.81818| 195.92278184944917|16001.895398150551|      14.31|    89.3|     0.068|                0.059|        0.156| 24608.65447| 12731.97556|    4|   4|
|24585.64824|  863.5604592333875| 23722.08778076661|      13.94|   63.93|     0.075|                0.055|        0.111| 40777.62712| 24995.74468|    2|  21|
|    15424.0|-45.211934184913844|15469.211934184914|      16.78|    70.4|     0.081|                0.022|        0.163| 23939.03122| 13113.23829|    4|   2|
|14908.91566|-24.938632667284764|14933.854292667285|      15.18|   61.48|     0.079|                0.099|        0.115| 24607.59494| 14819.45289|    1|   6|
|21402.88401|-3732.2126352004198| 25135.09664520042|      25.04|    84.6|     4.919|                0.077|        0.137| 34278.71254| 21474.55121|    8|   0|
|15735.06073| -554.9322175014531|16289.992947501452|      16.96|    76.7|     4.923|                0.051|        0.148| 26716.32787| 17030.34056|    5|   1|
|9889.156627|-148.61007481080196|10037.766701810802|        7.3|    80.3|     4.914|                0.073|        0.111| 21870.76923| 17066.52893|   11|   3|
|24105.32915| -448.1907964058955|24553.519946405897|      27.88|   44.28|     4.906|                491.6|        48.52| 37801.19867| 24930.09504|    8|  16|
|12885.59271|-1579.2532440973137|14464.845954097314|      21.15|    74.3|      4.92|                207.9|        178.0| 35801.48796| 23127.38589|   10|  13|
|11606.74699|-223.03101017214976| 11829.77800017215|      20.84|   60.14|     0.073|                248.5|        238.2| 29101.53846| 26590.90909|   11|  13|
|25060.43077|-1031.7496015737925| 26092.18037157379|      19.39|   66.76|     0.076|                0.051|          0.1| 40472.58278| 22333.47193|    6|   0|
|14449.20603|  473.1295875085689| 13976.07644249143|      13.52|   62.08|     4.921|                0.055|        0.096| 22863.05085| 13094.22492|    2|   4|
|11933.73349|-1354.4719876607323|13288.205477660733|      12.93|   60.75|     0.082|                 2.28|        2.255| 32717.87072| 27707.88585|   12|  17|
|40151.47335|  6134.128575574119| 34017.34477442588|      27.39|    82.3|     4.902|                23.58|        20.08| 49915.73807| 34133.47413|    8|  19|
|16298.93417|-1384.4411726534017|17683.375342653402|      21.72|   51.65|     4.905|                 0.15|        0.133| 23845.50499| 15338.96515|    8|   6|
+-----------+-------------------+------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+

-------------------------------------------
Batch: 2
-------------------------------------------
+-----------+-------------------+------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|      label|           residual|        prediction|Temperature|Humidity|Wind_Speed|General_Diffuse_Flows|Diffuse_Flows|Power_Zone_1|Power_Zone_2|Month|Hour|
+-----------+-------------------+------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|15886.45161|-1794.1553541388057|17680.606964138806|      13.25|    83.4|     0.078|                229.0|        217.1| 33653.10638| 20612.19512|    3|  11|
|25159.35484|  543.6870959447733|24615.667744055227|      13.52|   53.24|     0.084|                0.066|        0.115| 42967.14894| 25763.41463|    3|  20|
|23948.86432| 1484.3403262177635|22464.523993782237|      13.38|   58.95|     0.085|                0.051|          0.1| 39209.49153| 22840.12158|    2|  22|
|26519.27273| 1675.0286286468508| 24844.24410135315|      17.31|   69.24|     0.072|                0.062|        0.152|  40400.6028| 24888.39104|    4|  21|
|20310.03064| 1614.6547158679132|18695.375924132088|      21.58|    81.3|     0.265|                0.084|        0.115| 39555.39823| 23665.69647|    9|  22|
+-----------+-------------------+------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+

-------------------------------------------
Batch: 3
-------------------------------------------
+-----------+------------------+------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|      label|          residual|        prediction|Temperature|Humidity|Wind_Speed|General_Diffuse_Flows|Diffuse_Flows|Power_Zone_1|Power_Zone_2|Month|Hour|
+-----------+------------------+------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|25339.35484|-677.9741550978797| 26017.32899509788|      11.78|    78.5|     0.083|                 7.02|        6.512| 44780.93617| 26484.14634|    3|  19|
|17135.27638| 315.8419007521261|16819.434479247873|      13.84|    72.4|     0.073|                146.1|        145.1| 31545.76271| 18751.36778|    2|  11|
| 42940.9205| 6780.887419429491| 36160.03308057051|      29.54|   47.65|     0.068|                0.256|        0.204| 48452.89037| 31830.37975|    7|  20|
| 12471.2462|129.20783187668712|12342.038368123312|      18.69|    89.2|     0.064|                 72.7|        61.46|  32770.2407| 20162.24066|   10|   9|
|15944.09639|187.52000472520558|15756.576385274795|      16.32|   59.85|     4.918|                0.044|        0.137| 25014.68354| 14947.11246|    1|   1|
+-----------+------------------+------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+

-------------------------------------------
Batch: 4
-------------------------------------------
+-----------+------------------+------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|      label|          residual|        prediction|Temperature|Humidity|Wind_Speed|General_Diffuse_Flows|Diffuse_Flows|Power_Zone_1|Power_Zone_2|Month|Hour|
+-----------+------------------+------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|29811.15987| 2083.429798457386|27727.730071542614|      24.87|    88.6|     4.917|                 0.08|        0.133| 37558.26859| 26291.02429|    8|   0|
|16628.36364|-477.1017104154853|17105.465350415485|      13.57|    84.9|     4.923|                0.073|        0.159| 25358.88052| 13850.10183|    4|   4|
|33344.20063|  778.405686340695|32565.794943659304|      23.58|   64.55|     4.902|                 0.08|        0.089| 48196.04883|  31662.5132|    8|  21|
|20281.10769| 4611.334277918992| 15669.77341208101|      25.99|   63.48|     4.919|                810.0|        53.28| 28723.70861| 16476.92308|    6|  15|
|21327.09677|1653.4008538275666|19673.695916172433|      10.34|    88.8|     0.077|                0.029|        0.093| 35172.76596|  21519.5122|    3|  23|
+-----------+------------------+------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+

-------------------------------------------
Batch: 5
-------------------------------------------
+-----------+-------------------+------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|      label|           residual|        prediction|Temperature|Humidity|Wind_Speed|General_Diffuse_Flows|Diffuse_Flows|Power_Zone_1|Power_Zone_2|Month|Hour|
+-----------+-------------------+------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|17484.04858| 1569.2833246226382| 15914.76525537736|      24.82|   58.89|     0.071|                572.3|        360.8| 33061.77049| 18947.36842|    5|  14|
| 31553.4728| -555.0758067042807| 32108.54860670428|      32.39|   37.95|      4.91|                855.0|        61.56| 43719.86711| 27573.41772|    7|  12|
|18061.21457| -887.4071601123142|18948.621730112314|      18.61|   66.43|     4.925|                904.0|        341.9| 36813.63934| 23030.34056|    5|  12|
|11531.67173| 1669.7879157263833| 9861.883814273617|       19.6|    74.3|      0.23|                0.077|        0.174|  26083.8512| 15034.85477|   10|   3|
|24087.79899|  3507.804860761011| 20579.99412923899|      15.53|   60.69|     0.084|                135.2|        147.3| 36213.55932|   27556.231|    2|  18|
|33553.80753|  2719.395702441783|30834.411827558215|      33.85|   30.91|     4.904|                825.0|         95.2| 41302.32558| 30596.20253|    7|  12|
|10184.93927|  778.5652619587781| 9406.374008041223|      19.32|    78.5|     0.067|                42.66|         34.0| 20975.21311| 11476.16099|    5|   7|
|18616.17555| 433.89976803449827|  18182.2757819655|      23.65|    82.6|      4.92|                172.3|        64.48| 27578.95671| 18262.30201|    8|   8|
|16140.21609| -683.7596191431749|16823.975709143175|      15.15|   64.75|     0.082|                 0.07|        0.085| 37499.61977|  32443.0807|   12|  21|
|18768.73846|-1106.7400086592934|19875.478468659294|      24.29|   56.65|     0.073|                826.0|        104.9| 35869.66887| 22180.04158|    6|  14|
+-----------+-------------------+------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+

-------------------------------------------
Batch: 6
-------------------------------------------
+-----------+-------------------+------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|      label|           residual|        prediction|Temperature|Humidity|Wind_Speed|General_Diffuse_Flows|Diffuse_Flows|Power_Zone_1|Power_Zone_2|Month|Hour|
+-----------+-------------------+------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|17384.72727|-1227.9942480938917| 18612.72151809389|      23.62|   43.01|     0.085|                732.0|        153.5| 33282.75565| 21764.96945|    4|  14|
|18441.33739| -2637.553709646789| 21078.89109964679|      20.19|    87.9|     4.922|                0.077|        0.107| 44082.27571| 28620.74689|   10|  20|
|30179.74895|  265.5384262505031|29914.210523749498|      31.98|   31.52|     4.905|                673.2|        56.95| 39867.10963| 27748.10127|    7|  10|
| 18702.6506|  877.3687369963664|17825.281863003634|      20.08|    79.7|     0.066|                0.102|        0.041| 36135.38462| 30804.54545|   11|  21|
|23934.19355| 2158.7140952975133|21775.479454702487|      14.82|    76.2|     0.072|                102.4|        117.2|     38592.0| 26564.63415|    3|  18|
+-----------+-------------------+------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+

-------------------------------------------
Batch: 7
-------------------------------------------
+-----------+-------------------+------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|      label|           residual|        prediction|Temperature|Humidity|Wind_Speed|General_Diffuse_Flows|Diffuse_Flows|Power_Zone_1|Power_Zone_2|Month|Hour|
+-----------+-------------------+------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|13467.45659| 1268.2222092547327|12199.234380745267|      20.33|    57.1|     4.924|                530.0|        44.66| 31004.60177| 16540.54054|    9|  10|
|20150.97179|  2651.180777080135|17499.791012919864|      22.58|   50.42|     4.902|                244.2|        28.22| 26952.45283| 18262.30201|    8|   8|
| 17066.0241| 185.61216128232263|16880.411938717676|      10.31|    72.2|     0.086|                0.048|        0.108| 27232.40506| 17208.51064|    1|   0|
|15445.16129|-224.40448191990072|  15669.5657719199|      15.67|    87.9|     4.908|                0.018|        0.104| 25613.61702|     14550.0|    3|   1|
|11140.66869|-1998.8367253433953|13139.505415343396|      17.48|    83.0|      0.08|                 93.7|         82.0| 33116.84902| 26772.19917|   10|  14|
+-----------+-------------------+------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+

-------------------------------------------
Batch: 8
-------------------------------------------
+-----------+-------------------+------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|      label|           residual|        prediction|Temperature|Humidity|Wind_Speed|General_Diffuse_Flows|Diffuse_Flows|Power_Zone_1|Power_Zone_2|Month|Hour|
+-----------+-------------------+------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|12231.97568|-1417.3879597280138|13649.363639728013|      20.66|    82.3|     4.915|                224.2|        171.3| 33885.68928| 25674.27386|   10|  13|
|19729.65517| -5956.219772588614|25685.874942588616|       27.2|   47.22|     4.933|                135.5|        149.1| 39757.42508| 23230.83421|    8|  18|
|17815.27273| -1663.426191598417|19478.698921598418|       20.8|   60.89|     0.081|                159.5|        127.6| 33580.36598| 19990.63136|    4|  15|
|23948.86432| 1484.3403262177635|22464.523993782237|      13.38|   58.95|     0.085|                0.051|          0.1| 39209.49153| 22840.12158|    2|  22|
|23948.86432| 1484.3403262177635|22464.523993782237|      13.38|   58.95|     0.085|                0.051|          0.1| 39209.49153| 22840.12158|    2|  22|
|23948.86432| 1484.3403262177635|22464.523993782237|      13.38|   58.95|     0.085|                0.051|          0.1| 39209.49153| 22840.12158|    2|  22|
|19003.17992| -3470.790193344328|22473.970113344327|      24.08|   60.36|     4.903|                0.102|         0.13| 24577.27575| 16556.96203|    7|   5|
+-----------+-------------------+------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+

-------------------------------------------
Batch: 9
-------------------------------------------
+-----------+------------------+------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|      label|          residual|        prediction|Temperature|Humidity|Wind_Speed|General_Diffuse_Flows|Diffuse_Flows|Power_Zone_1|Power_Zone_2|Month|Hour|
+-----------+------------------+------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|16925.80645|-877.3956323936254|17803.202082393625|      14.68|   66.88|     0.081|                62.35|        55.87| 33028.08511| 20352.43902|    3|  18|
|26897.72308| 1481.382051453249| 25416.34102854675|      20.67|    83.5|     0.066|                0.051|         0.13|  41998.4106| 24687.31809|    6|  21|
|11531.67173|1669.7879157263833| 9861.883814273617|       19.6|    74.3|      0.23|                0.077|        0.174|  26083.8512| 15034.85477|   10|   3|
|11531.67173|1669.7879157263833| 9861.883814273617|       19.6|    74.3|      0.23|                0.077|        0.174|  26083.8512| 15034.85477|   10|   3|
|11531.67173|1669.7879157263833| 9861.883814273617|       19.6|    74.3|      0.23|                0.077|        0.174|  26083.8512| 15034.85477|   10|   3|
|16828.91566| 3322.899717595874|13506.015942404125|      21.11|    53.5|     0.075|                459.8|        52.94| 31870.76923| 23972.72727|   11|  11|
|16557.10843|-859.4774681239833|17416.585898123983|      17.93|   62.25|     0.088|                120.3|        121.9| 31910.88608| 19520.97264|    1|  16|
+-----------+------------------+------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+

-------------------------------------------
Batch: 10
-------------------------------------------
+-----------+------------------+------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|      label|          residual|        prediction|Temperature|Humidity|Wind_Speed|General_Diffuse_Flows|Diffuse_Flows|Power_Zone_1|Power_Zone_2|Month|Hour|
+-----------+------------------+------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|28043.81538| 43.58763665946026| 28000.22774334054|       20.8|   51.62|     0.079|                 9.77|         8.53| 46181.72185| 27913.09771|    6|  20|
|    25664.0|1408.0707700111925|24255.929229988807|      16.11|    64.8|     0.082|                0.018|        0.085| 40040.99031| 22076.57841|    4|  22|
|9871.807229|351.01030565606925|  9520.79692334393|      17.76|   52.69|     0.078|                 0.04|        0.074| 22258.46154| 17014.46281|   11|   2|
|24641.00313| 78.87758479956028| 24562.12554520044|      26.28|    89.8|     4.911|                196.2|        143.0| 36803.90677| 26195.98733|    8|   9|
|38297.68025|  4456.37754708343| 33841.30270291657|      29.16|   50.12|     4.905|                1.024|        0.926| 49570.52164| 36391.55227|    8|  20|
+-----------+------------------+------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+

-------------------------------------------
Batch: 11
-------------------------------------------
+-----------+-------------------+------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|      label|           residual|        prediction|Temperature|Humidity|Wind_Speed|General_Diffuse_Flows|Diffuse_Flows|Power_Zone_1|Power_Zone_2|Month|Hour|
+-----------+-------------------+------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
| 17309.1498|  55.03056232820745| 17254.11923767179|      17.62|    77.0|     0.069|                0.055|        0.126| 29020.32787| 17981.42415|    5|   0|
|10350.63317|  306.1493726884928|10044.483797311506|      6.442|   65.74|     0.088|                0.066|        0.126|  20764.0678| 13061.39818|    2|   7|
|11916.43725| -294.6319425027723|12211.069192502773|      18.28|    78.2|     0.069|                181.9|        166.6| 25721.70492|  15637.1517|    5|   7|
|26427.20648|-1341.4838537511314|27768.690333751132|      18.25|    76.8|      4.92|                0.037|        0.104|  46671.7377| 28246.43963|    5|  21|
|25230.84639|-1894.9774838282647|27125.823873828263|      26.67|    83.1|     4.913|                123.3|         93.9| 40281.64262| 28473.07286|    8|  15|
+-----------+-------------------+------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+

-------------------------------------------
Batch: 12
-------------------------------------------
+-----------+-------------------+------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|      label|           residual|        prediction|Temperature|Humidity|Wind_Speed|General_Diffuse_Flows|Diffuse_Flows|Power_Zone_1|Power_Zone_2|Month|Hour|
+-----------+-------------------+------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|16679.87743| -273.3123491750048|16953.189779175005|       21.0|    78.2|     4.917|                0.091|        0.093| 36401.41593| 20881.49688|    9|  22|
|27138.80878|  1525.408540903085|25613.400239096914|      25.83|    88.6|     4.908|                0.059|        0.163| 34483.28524| 24223.02006|    8|   1|
| 13008.1459|-378.31820393880116|  13386.4641039388|      25.57|   42.88|     4.919|                460.7|        179.4| 35076.76149| 22511.20332|   10|  15|
|16298.93417|-1384.4411726534017|17683.375342653402|      21.72|   51.65|     4.905|                 0.15|        0.133| 23845.50499| 15338.96515|    8|   6|
|16298.93417|-1384.4411726534017|17683.375342653402|      21.72|   51.65|     4.905|                 0.15|        0.133| 23845.50499| 15338.96515|    8|   6|
|16298.93417|-1384.4411726534017|17683.375342653402|      21.72|   51.65|     4.905|                 0.15|        0.133| 23845.50499| 15338.96515|    8|   6|
|17367.27273|  263.2265852471173|17104.046144752883|      16.74|   65.33|     0.079|                 0.04|          0.1| 26338.51453| 14993.89002|    4|   0|
+-----------+-------------------+------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+

-------------------------------------------
Batch: 13
-------------------------------------------
+-----------+-------------------+------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|      label|           residual|        prediction|Temperature|Humidity|Wind_Speed|General_Diffuse_Flows|Diffuse_Flows|Power_Zone_1|Power_Zone_2|Month|Hour|
+-----------+-------------------+------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|18692.05312|  3246.388513383068|15445.664606616932|       23.7|   62.15|     0.273|                 0.08|          0.1| 35018.76106| 21057.38046|    9|  23|
|10313.19838|-1132.4962560869444|11445.694636086944|      19.13|    79.3|      0.07|                29.97|        23.51|  20912.2623| 11238.39009|    5|   6|
|32374.15385|  5706.553660183959| 26667.60018981604|      22.72|   63.08|      4.92|                0.106|        0.063| 43002.91391| 26928.89813|    6|  22|
|17783.13253| -3248.040082444066|21031.172612444065|      12.88|   61.93|     4.918|                0.951|        1.027| 40252.30769| 33913.63636|   11|  18|
|16038.56997| 3376.8205417106456|12661.749428289355|      25.33|   48.48|     4.926|                451.3|        52.99| 31533.45133| 17584.61538|    9|  16|
+-----------+-------------------+------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+

-------------------------------------------
Batch: 14
-------------------------------------------
+-----------+-------------------+------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|      label|           residual|        prediction|Temperature|Humidity|Wind_Speed|General_Diffuse_Flows|Diffuse_Flows|Power_Zone_1|Power_Zone_2|Month|Hour|
+-----------+-------------------+------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|20402.89157|  550.4650509495659|19852.426519050434|       19.2|    72.6|      0.07|                0.124|        0.093| 39304.61538| 32202.89256|   11|  18|
|17505.54217| 3571.2946367729855|13934.247533227015|      22.28|   50.37|     0.074|                360.2|        110.1| 32695.38462| 24024.79339|   11|  15|
|17936.05016|-3314.9121102636564|21250.962270263655|      24.12|    82.0|     4.921|                225.0|         88.8| 32392.80799| 20470.96093|    8|   9|
|20765.53846| -934.8753974919418| 21700.41385749194|      30.41|   27.42|     3.688|                603.4|        49.18| 37687.94702| 23055.71726|    6|  16|
|16192.77108|  4698.434023430966|11494.337056569035|      20.01|    77.3|     0.074|                159.6|        159.5| 28178.46154| 24147.52066|   11|  10|
+-----------+-------------------+------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+

-------------------------------------------
Batch: 15
-------------------------------------------
+-----------+-------------------+------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|      label|           residual|        prediction|Temperature|Humidity|Wind_Speed|General_Diffuse_Flows|Diffuse_Flows|Power_Zone_1|Power_Zone_2|Month|Hour|
+-----------+-------------------+------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|9692.196879| -2883.959364429258|12576.156243429257|      14.04|   69.95|     0.086|                36.35|        35.69| 31793.15589| 26794.72231|   12|  16|
| 20776.9279|-358.05679232770854|21134.984692327707|      27.02|   53.92|     4.902|                0.113|        0.089| 28333.31853| 20942.34424|    8|   4|
|16840.62696|  -4194.62339225721| 21035.25035225721|      24.29|    89.3|     4.916|                0.069|        0.148| 28314.13984| 17239.70433|    8|   3|
|26330.58462|  3242.033094308943| 23088.55152569106|      21.38|    82.5|     4.919|                0.066|        0.137| 34502.78146| 21689.81289|    6|   0|
|18691.93846| -242.1818606104389| 18934.12032061044|      23.96|   38.84|      0.08|                869.0|        293.5| 35691.65563| 21959.25156|    6|  15|
+-----------+-------------------+------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+

-------------------------------------------
Batch: 16
-------------------------------------------
+-----------+------------------+------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|      label|          residual|        prediction|Temperature|Humidity|Wind_Speed|General_Diffuse_Flows|Diffuse_Flows|Power_Zone_1|Power_Zone_2|Month|Hour|
+-----------+------------------+------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|14692.34171|1348.6273707091732|13343.714339290827|       13.8|    72.1|     0.074|                0.088|          0.1|  22557.9661| 13272.94833|    2|   2|
|25347.46988|1066.8012648485128|24280.668615151488|      11.46|   53.89|     0.086|                0.059|        0.122| 41085.56962| 27114.89362|    1|  21|
|9311.884754| 1916.139355911204| 7395.745398088797|       7.26|    90.1|     0.082|                0.015|        0.122| 21463.11787| 16293.34152|   12|   4|
|14970.21106| 47.37518180599545|14922.835878194004|      11.16|   65.88|     4.917|                0.048|        0.137| 24174.91525| 14195.74468|    2|   5|
|13352.46201|-947.9886318623048|14300.450641862304|      23.91|   58.12|     0.075|                44.49|        39.28| 35889.71554| 21969.70954|   10|  17|
+-----------+------------------+------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+

## **Producing the Data**
At this point, the `power_streaming_data.csv` file should be uploaded into the main directory in `jupyterhub`. Additionally, the `Loring_FinalProject.py` file reads in the `power_streaming_data.csv` file and writes a loop that randomly samples some rows from this file, outputs them to a `.csv` (removing the indices), and pauses for 10 seconds in between outputting of datasets.

After running the above line of code to start the query, we can run the loop from the `Loring_FinalProject.py` file in a python console. Once we do this, we will see output here in this notebook right above the start of this section. Then the query will be stopped. Please see the video uploaded to Moodle within the Final Project assignment to see a recording of this process play out in real time.

In [34]:
query.stop()